### ISSUE TITLE
Author name change in CPAN is not reflected in Profile

### ISSUE THREAD

**Issue by mickeyn** [metacpan/metacpan-api#1007]
This issue reported by @neilb on IRC.

It refers to a case where a name change in CPAN (00whois.xml) is not reflected in the author profile (no change happens during the run of the Author script cron).

The reason (at least one of them) for this to happen is that the **user** which is also an **author** has changed their name in the Profile page and at that moment an `updated` field is set with current timestamp.

The existence of this timestamp regardless of its value, is used to determine whether a change in CPAN will override the name field in the `author` details.
(the timestamp is used and compared for latest version only in the case the author has a  `author-*.json` file in their CPAN directory)

I will create an MR to adjust the tooling to allow manual override (force CPAN data) in special cases (per author).

The question that remains is - 
Should the logic where we reject changes from CPAN when the profile on MetaCPAN was changed stay as is?

**Comment by haarg** [comment]
This is basically the same issue as #621

**Comment by mickeyn** [comment]
True, only my question was in a broader sense then just in the case of custodial accounts.
My current intention is: 
1. to update the tooling to give more flexibility to manual handling.
2. fix the custodial accounts case to be handled automatically
If that is all we need, the coming PRs will resolve both issues.

**Comment by oalders** [comment]
I think the logic is mostly ok. I don't recall that we've needed manual overrides too often. I mean, it's a bit confusing, but I think the general idea is that we use the static files as a starting point and assume people aren't going to be updating things in two places.

**Comment by mickeyn** [comment]
that answers my question :)
