### ISSUE TITLE
Invalid JSON Payload produces Plain Text Response

### ISSUE THREAD

**Issue by domibay-hugo** [metacpan/metacpan-api#1029]
I'm trying to use the MetaCPAN API to find packages to which certain file belongs.
like in:
```
Try/Tiny.pm not found in search path
```
so reproducing the example and accidentally producing invalid JSON the API crashes and produces an invalid JSON Response:
```
$ curl -XPOST https://fastapi.metacpan.org/v1/file/_search -d '{
  "query": {
    "match_all": {}
  },
  "size": 1000,
  "fields": [ "name", "status", "directory", "path", "distribution" ],
  "filter": {
    "and": [
      { "term" : { "path" : "/Tiny.pm" }  
    ]
  }
}'
Content-Type application/json had a problem with your request.
***ERROR***
, or } expected while parsing object/hash, at character offset 199 (before "]\n  }\n}") at /home/metacpan/carton/metacpan-api/lib/perl5/Catalyst/Action/Deserialize/JSON.pm line 35, <$fh> line 12.
```

**Comment by haarg** [comment]
What were you expecting to happen when you sent a malformed request?

**Comment by domibay-hugo** [comment]
I reproduced the call with the display of response headers
```
$ curl -D - -H "Accept: application/json" -XPOST https://fastapi.metacpan.org/v1/file/_search -d '{       
  "query": {
    "match_all": {}
  },           
  "size": 1000,                                                       
  "fields": [ "name", "status", "directory", "path", "distribution" ],
  "filter": {
    "and": [                              
      { "term" : { "path" : "/Tiny.pm" }  
    ]
  }
}'
HTTP/1.1 400 Bad Request
Connection: keep-alive
Content-Length: 273
Server: nginx
Content-Type: text/plain; charset=UTF-8
Cache-Control: private
Accept-Ranges: bytes
Via: 1.1 varnish, 1.1 varnish
Date: Thu, 08 Jul 2021 11:16:35 GMT
X-Served-By: cache-lhr7380-LHR, cache-mad22081-MAD
X-Cache: MISS, MISS
X-Cache-Hits: 0, 0
X-Timer: S1625742996.617790,VS0,VE54

Content-Type application/json had a problem with your request.
***ERROR***
, or } expected while parsing object/hash, at character offset 201 (before "]\n  }\n}") at /home/metacpan/carton/metacpan-api/lib/perl5/Catalyst/Action/Deserialize/JSON.pm line 35, <$fh> line 12.
```

When the application asked for `content-type: application/json` the polite behaviour would be to respond with a JSON Response.

Also for production usage the disclosure of the server internal system structure as it happens when dumping the _Perl_ Exceptions as they are can result **Security Issues**:
```
at /home/metacpan/carton/metacpan-api/lib/perl5/Catalyst/Action/Deserialize/JSON.pm line 35, <$fh> line 12.
```

**Comment by haarg** [comment]
The code running on the server, including its internal structure, is all public.

**Comment by oalders** [comment]
> When the application asked for content-type: application/json the polite behaviour would be to respond with a JSON Response.

I don't think we advertise anywhere that 4xx responses will contain a JSON body. If we do, we should change that. I'm not opposed to wrapping exceptions and returning JSON, but we'd need a volunteer to do that. I think, for the moment, this gets the job done and hopefully the client would check the content type on a 4xx response before attempting to parse it.

**Comment by jberger** [comment]
Surely metacpan cannot be expected to handle any value of the Accept header that you send. Yes it would be nice if there was a json response for errors, but as @oalders says all that is guaranteed is that the response be the type indicated in the responses' Content-Type header. Now metacpan could decide to be more strict and if it cannot respond via any of the given options in the Accept header, it could reply with a 406, but that is less helpful in almost all cases, including this one, IMO.

**Comment by domibay-hugo** [comment]
Looking at the **Response Headers** the client can understand that the Request was wrong.
So up to this point as @oalders stated the Response gets the job done.

Still this issue is about the expected Response and the Impression that is given to the Client.

I was rather expecting a JSON Response as it can seen in:
```
$ curl -Ls https://gist.github.com/metacpan-user/5706053/raw/body.json
{
  "fields": [
    "distribution"
  ],
  "filter": {
    "term": {
      "status": "latest"
    }
  },
  "size": 100
}
$ curl -D - -H "Accept: application/json" -XPOST 'https://fastapi.metacpan.org/search/reverse_dependencies/MetaCPAN-API' -d "$(curl -Ls https://gist.github.com/metacpan-user/5706053/raw/body.json)"
HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Length: 34
Server: nginx
Content-Type: application/json; charset=utf-8
Cache-Control: private
Accept-Ranges: bytes
Via: 1.1 varnish, 1.1 varnish
Date: Fri, 09 Jul 2021 08:18:43 GMT
X-Served-By: cache-lhr7368-LHR, cache-mad22076-MAD
X-Cache: MISS, MISS
X-Cache-Hits: 0, 0
X-Timer: S1625818724.653327,VS0,VE48
Vary: Accept-Encoding

{"code":404,"message":"Not found"}
```

The wellformed JSON Response shows a **composed and resilient Awareness** of the User Error with a prepared Server Response.

As @haarg mentioned the code is all public so I took a look at the code and noticed
at [JSON Deserialization without Error Handling](https://github.com/metacpan/metacpan-api/blob/45f6e11aff84569aa7a410c7513b60f710030131/lib/Catalyst/Action/Deserialize/MetaCPANSanitizedJSON.pm#L45)
that the JSON Deserialize has a `try` block without a corresponding `catch` block
so the Exception will drop into the bottom `catch` block at
[Catch All Block](https://github.com/metacpan/metacpan-api/blob/45f6e11aff84569aa7a410c7513b60f710030131/lib/Catalyst/Action/Deserialize/MetaCPANSanitizedJSON.pm#L60)

but rather a little function like:
```perl
sub bad_request: Private {
    my ( $self, $c, $description ) = @_;
    $c->cdn_never_cache(1);

    $c->res->code(400);
    $c->stash( { message => 'Bad Request' } );
    $c->stash( { description => $description } );
}
```
As seen in my branch:
[JSON Bad Request Response Proposal](https://github.com/domibay-hugo/metacpan-api/tree/domibay-hugo/no-1029_bad-request-json)

**Comment by oalders** [comment]
We could certainly review a PR with a similar change if it had accompanying tests.

**Comment by domibay-hugo** [comment]
I managed to get a working solution and a test which proves it.
Which looks like:
```
[2021/07/15 14:58:35] [DEBUG] [/file/_search] Path is "file/_search"
[2021/07/15 14:58:35] [DEBUG] [/file/_search] "POST" request for "file/_search" from "127.0.0.1"
arr desc dmp:
(
  "malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before \"some content as inva...\")",
  "/usr/local/lib/perl5/site_perl/5.30.1/Catalyst/Action/Deserialize/JSON.pm",
  "line 35, <\$fh> line 1.",
)
'Catalyst::Action::execute' : Signal to 'MetaCPAN::Server::Controller::bad_request_json'
'MetaCPAN::Server::Controller::_wrapped_end' : Signal to 'Class::MOP::Class:::before'
Status Code [400]
Content-Type: 'text/plain'
Response Body: 'Content-Type application/json had a problem with your request.
***ERROR***
catalyst_detach
'
[2021/07/15 14:58:35] [DEBUG] [/file/_search] Response Code: 400; Content-Type: application/json; charset=utf-8; Content-Length: unknown
[2021/07/15 14:58:35] [INFO] [/file/_search] Request took 0.025241s (39.618/s)
.--------------------------------------------------------------------------------+-----------.
| Action                                                                         | Time      |
+--------------------------------------------------------------------------------+-----------+
| /file/search                                                                   | 0.020377s |
|  -> /bad_request_json                                                          | 0.000925s |
|   -> MetaCPAN::Server::View::JSON->process                                     | 0.000342s |
| /file/end                                                                      | 0.000530s |
|  -> MetaCPAN::Server::View::JSON->process                                      | 0.000198s |
'--------------------------------------------------------------------------------+-----------'

ok 1 - POST /file/_search
ok 2 - 400 Bad Request
Status Code: [400]
Content-Type: 'application/json; charset=utf-8'
Response Body (max 1000): '{"message":"Bad Request","description":{"exception_type":"Mojo::Exception","lines":"line 35, <$fh> line 1.","description":"malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before \"some content as inva...\")","file":"/usr/local/lib/perl5/site_perl/5.30.1/Catalyst/Action/Deserialize/JSON.pm"}}'
1..2
```

Although it works I'm not very satisfied with it because there exist **2 "_bad_request_" Actions**
```
[2021/07/15 14:58:35] [DEBUG] [[undef]] Loaded Private actions:
.------------------------+----------------------------------------------+------------------------.
| Private                | Class                                        | Method                 |
+------------------------+----------------------------------------------+------------------------+
| /end                   | MetaCPAN::Server::Controller::Root           | end                    |
| /not_found             | MetaCPAN::Server::Controller::Root           | not_found              |
| /all                   | MetaCPAN::Server::Controller::Root           | all                    |
| /bad_request           | MetaCPAN::Server::Controller::Root           | bad_request            |
| /mapping               | MetaCPAN::Server::Controller::Root           | mapping                |
| /join                  | MetaCPAN::Server::Controller::Root           | join                   |
| /search                | MetaCPAN::Server::Controller::Root           | search                 |
| /default               | MetaCPAN::Server::Controller::Root           | default                |
| /bad_request_json      | MetaCPAN::Server::Controller::Root           | bad_request_json       |
| /get                   | MetaCPAN::Server::Controller::Root           | get                    |
| /robots                | MetaCPAN::Server::Controller::Root           | robots                 |
| /not_allowed           | MetaCPAN::Server::Controller::Root           | not_allowed            |
```
And I needed to define a new Action `bad_request_json()` because otherwise there is a Name Clash and the Controller would only execute the **Default Action**.

I could not find a nice way to override `MetaCPAN::Server::Controller::Root::bad_request()`

So I took the idea from
https://stackoverflow.com/questions/39508412/whats-the-best-practice-for-error-handling-with-catalystcontrollerrest?rq=1
and as the comment there suggests the Source Code at
https://metacpan.org/release/DAVEWOOD/Catalyst-ControllerRole-CatchErrors-0.05/source/lib/Catalyst/ControllerRole/CatchErrors.pm
which overrides the `end()` Action.

Also I can see that  after the Custom Metod `bad_request_json()` still the Default Action is invoked and overrides the `Content-Type` and writes its own body:
```
'Catalyst::Action::execute' : Signal to 'MetaCPAN::Server::Controller::bad_request_json'
'MetaCPAN::Server::Controller::_wrapped_end' : Signal to 'Class::MOP::Class:::before'
Status Code [400]
Content-Type: 'text/plain'
Response Body: 'Content-Type application/json had a problem with your request.
***ERROR***
catalyst_detach
'
```

**Comment by domibay-hugo** [comment]
This issue is getting even more stranger since I inserted a "_after 'execute'_" Hook in `Catalyst::Action::Deserialize::MetaCPANSanitizedJSON` as on:
[Override Catalyst Actions](https://metacpan.org/dist/Catalyst-Manual/view/lib/Catalyst/Manual/Actions.pod#WRITING-YOUR-OWN-ACTIONS)
and it reports that the **Response is altered** between 
* `Catalyst::Action::Deserialize::MetaCPANSanitizedJSON::_wrapped_execute`
* and `MetaCPAN::Server::Controller::_wrapped_end`
as seen in this Debug Output:
```
'Catalyst::Action::execute' : Signal to 'MetaCPAN::Server::Controller::bad_request_json'
'Catalyst::Action::Deserialize::MetaCPANSanitizedJSON::_wrapped_execute' : Signal to 'Class::MOP::Class:::after'
Status Code [400]
Content-Type: 'application/jsoncharset=utf-8'
Response Body: '{"message":"Bad Request","description":{"lines":"line 35, <$fh> line 1.","file":"/usr/local/lib/perl5/site_perl/5.30.1/Catalyst/Action/Deserialize/JSON.pm","description":"malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before \"some content as inva...\")","exception_type":"Mojo::Exception"}}'
execute finished - no errors.
'MetaCPAN::Server::Controller::_wrapped_end' : Signal to 'Class::MOP::Class:::before'
Status Code [400]
Content-Type: 'text/plain'
Response Body: 'Content-Type application/json had a problem with your request.
***ERROR***
catalyst_detach
'
```
In the "_after 'execute'_" Hook the Response Body is correctly built with the **JSON View**.
But after then it is overwritten again.
I supposed it had to do with the Context Error List but there aren't any accumulated Errors in there as well.
```
execute finished - no errors.
```

**Comment by haarg** [comment]
#1034 should fix this.

**Comment by domibay-hugo** [comment]
@haarg from your Pull Request I came to the **Source Code** where the Message I have always seen is generated at:
[`Catalyst::Action::SerializeBase::serialize_bad_request()`](
https://github.com/perl-catalyst/Catalyst-Action-REST/blob/f789417d081b4d519ded07eec046c0b01661e25d/lib/Catalyst/Action/SerializeBase.pm#L177)
which overwrites the Response
Unfortunately this is somewhat **undocumented**
The documentation that I already saw before at
[Customize Errors for `Catalyst::Action::Deserialize`](https://metacpan.org/pod/Catalyst::Action::Deserialize#CUSTOM-ERRORS)
points to ->
[Deprecated `Catalyst::Controller::ActionRole`](https://metacpan.org/pod/Catalyst::Controller::ActionRole)
which **deprecates the Module without giving any valid alternative solution**

> 
Deprecated.
The maintainer of this distribution has indicated that it is deprecated and no longer suitable for use.

Still when looking on the Code I noticed that is not the only **Use Case** where an **Error 400** is issued.
So I was aiming for a much broader and reusable solution.

**Comment by domibay-hugo** [comment]
I adapted my test to reflect the solution.
Now the Control Flow shows that the Request goes directly from `/file/search` to `/file/end`.
```
[2021/07/30 13:31:38] [INFO] [/file/_search] *** Request 2 (0.667/s) [122] [Fri Jul 30 13:31:38 2021] ***
[2021/07/30 13:31:38] [DEBUG] [/file/_search] Path is "file/_search"
[2021/07/30 13:31:38] [DEBUG] [/file/_search] "POST" request for "file/_search" from "127.0.0.1"
'MetaCPAN::Server::Controller::_wrapped_end' : Signal to 'Class::MOP::Class:::before'
Status Code [400]
Content-Type: ''
[2021/07/30 13:31:38] [WARN] [/file/_search] Use of uninitialized value in print at /metacpan-api/t/api/../../lib/MetaCPAN/Server/Controller.pm line 270.
Response Body: ''
[2021/07/30 13:31:38] [DEBUG] [/file/_search] Response Code: 400; Content-Type: application/json; charset=utf-8; Content-Length: unknown
[2021/07/30 13:31:38] [INFO] [/file/_search] Request took 0.004619s (216.497/s)
.--------------------------------------------------------------------------------+-----------.
| Action                                                                         | Time      |
+--------------------------------------------------------------------------------+-----------+
| /file/search                                                                   | 0.000697s |
| /file/end                                                                      | 0.000693s |
|  -> MetaCPAN::Server::View::JSON->process                                      | 0.000244s |
'--------------------------------------------------------------------------------+-----------'

ok 4 - POST /file/_search
ok 5 - 400 Bad Request
ok 6 - similar match for JSON Pointer "/error"
Status Code: [400]
Content-Type: 'application/json; charset=utf-8'
Response Body (max 1000): '{"error":"Content-Type application/json had a problem with your request.\nmalformed JSON string, neither tag, array, object, number, string or atom,"}'
```
Strangely the Control Flow does not enter `/bad_request`
and also the Response is not set within `MetaCPAN::Server::Controller`.

Unfortunately the Information where within the Request the JSON is broken is cut off as it was:
"_ at character offset 0 (before \"some content as inva...\")_"

**Comment by domibay-hugo** [comment]
I also created a Test to check the `/bad_request` condition in:
[MetaCPAN::Server::Controller::search](https://github.com/metacpan/metacpan-api/blob/560817a8d823b64a133dab1ffa32f0e2ba375a5a/lib/MetaCPAN/Server/Controller.pm#L111)
This turned out to be a check for the Requested Result Size as it is given as `size` Parameter in the Search Query as in:
```
---
# name: Big Result
# version: 0.0.1
# abstract: Test a Big Result Request

query:
  query_string:
    query: "cpanfile"
filter:
  and:
    - term:
        status: "latest"
fields: ["module.name", "documentation", "release", "maturity", "status", "name", "path", "level", "download_url"]
size: 5001
```
Here the Control Flow enters the `/bad_request` Method and is also visible within `MetaCPAN::Server::Controller`
```
[2021/07/30 13:46:18] [INFO] [/file/_search] *** Request 1 (0.500/s) [134] [Fri Jul 30 13:46:18 2021] ***
[2021/07/30 13:46:18] [DEBUG] [/file/_search] Path is "file/_search"
[2021/07/30 13:46:18] [DEBUG] [/file/_search] "POST" request for "file/_search" from "127.0.0.1"
MetaCPAN::Server::Controller::search - size: '5001'
'MetaCPAN::Server::Controller::_wrapped_end' : Signal to 'Class::MOP::Class:::before'
Status Code [416]
Content-Type: 'application/jsoncharset=utf-8'
Response Body: '{"message":"size parameter exceeds maximum of 5000"}'
[2021/07/30 13:46:18] [DEBUG] [/file/_search] Response Code: 416; Content-Type: application/json; charset=utf-8; Content-Length: unknown
[2021/07/30 13:46:18] [INFO] [/file/_search] Request took 0.022319s (44.805/s)
.--------------------------------------------------------------------------------+-----------.
| Action                                                                         | Time      |
+--------------------------------------------------------------------------------+-----------+
| /file/search                                                                   | 0.017792s |
|  -> /bad_request                                                               | 0.000699s |
|   -> MetaCPAN::Server::View::JSON->process                                     | 0.000290s |
| /file/end                                                                      | 0.000445s |
|  -> MetaCPAN::Server::View::JSON->process                                      | 0.000162s |
'--------------------------------------------------------------------------------+-----------'

ok 1 - POST /file/_search
ok 2 - 416 Request Range Not Satisfiable
ok 3 - similar match for JSON Pointer "/message"
Request Query Size: '217'
Status Code: [416]
Content-Type: 'application/json; charset=utf-8'
Response Body (max 1000): '{"message":"size parameter exceeds maximum of 5000"}'
```
The Test shows that the Response is already correctly formatted as JSON.

**Comment by oalders** [comment]
Did you want to contribute the test?

**Comment by domibay-hugo** [comment]
If this is ok I could add the Test for **Error 416**
and look into the `MetaCPAN::Server::Action::Deserialize` about the missing information.

**Comment by oalders** [comment]
@domibay-hugo sure, that sounds good!

**Comment by domibay-hugo** [comment]
When writing the test I actually found that it is there where you most see the **Error 400** and 
also in the _MetaCPAN API Explorer_ when you craft the query manually to work with the _MetaCPAN API_
like in :
```
# Subtest: big result query
    # Subtest: check with 'release' controller
        ok 1 - GET /release/_search
        not ok 2 - code [416] as expected
        ok 3 - Content-type
cntnt: '{
   "error" : "Content-Type application/json had a problem with your request.\n, or ] expected while parsing array, at character offset 143 (before \": {\\n               ...\")\n"
}
'
        ok 4 - response is a JSON object
        not ok 5 - response includes field 'message'
        not ok 6 - response error message as expected
        1..6
    not ok 1 - check with 'release' controller
    # Subtest: check with 'file' controller

        #   Failed test 'code [416] as expected'
        #   at t/server/controller/bad_request.t line 50.
        #          got: '400'
        #     expected: '416'

        #   Failed test 'response includes field 'message''
        #   at t/server/controller/bad_request.t line 59.
Use of uninitialized value in pattern match (m//) at t/server/controller/bad_request.t line 60.

        #   Failed test 'response error message as expected'
        #   at t/server/controller/bad_request.t line 60.
        # Looks like you failed 3 tests of 6.
```
Any any hints on fixing complex `JSON` queries are dearly needed and most appreciated.

**Comment by oalders** [comment]
It's not clear to me what's going on with that error message? Is the regex that creates the message not working as expected?

**Comment by domibay-hugo** [comment]
Just looking on the Test Report I could already conclude by receiving an **Error 400** that there was an error in the `JSON` which was sent to the server:
```
        #   Failed test 'code [416] as expected'
        #   at t/server/controller/bad_request.t line 50.
        #          got: '400'
        #     expected: '416'
```
but I needed the **more detailed Error Message** to figure out where the Request went wrong.

On the other hand the test also shows some inconsistency in the behaviour of Error Reporting:
```
        #   Failed test 'response includes field 'message''
        #   at t/server/controller/bad_request.t line 59.
Use of uninitialized value in pattern match (m//) at t/server/controller/bad_request.t line 60.

        #   Failed test 'response error message as expected'
        #   at t/server/controller/bad_request.t line 60.
```

Most Methods in `MetaCPAN::Server::Controller` like 
* `not_found()`
* `internal_error()`
* `bad_request()`

populate a `message` field. 
While the **Error 400** populates an `error` field.

This alternated behaviour reduces the **Usability** which will affect Automated Clients and Web Sites which use the `message` field and make them fail and cause Data Loss in case there was an issue in the `JSON` code and an **Error 400** was received. Just as it is seen in the test.
