### ISSUE TITLE
Some release is missing the "distribution" and "name" fields

### ISSUE THREAD

**Issue by akarelas** [metacpan/metacpan-api#1037]
The release with archive = "DBD-CSV-0.24_02.tbz" and date = "2009-06-20T19:24:12" is missing its name and distribution fields.

I saw this by running the following script:

```perl
#!/usr/bin/env perl

use v5.34;
use warnings;
use FindBin '$RealBin';

use MetaCPAN::Client;
use DateTime::Format::RFC3339;
use DDP;

my $mcpan = MetaCPAN::Client->new;

my $min_dt = DateTime->new(
    year      => 2009,
    month     => 6,
    day       => 20,
    hour      => 19,
    minute    => 24,
    time_zone => 'UTC',
);
my $max_dt = $min_dt->clone->add(minutes => 1);

my $releases = $mcpan->all('releases', {
    es_filter => {
        and => [
            { term => { authorized => 1 } },
            { term => { maturity => 'released' } },
            {
                range => {
                    date => {
                        gte => DateTime::Format::RFC3339->format_datetime($min_dt),
                        defined $max_dt ? ( lte => DateTime::Format::RFC3339->format_datetime($max_dt) ) : (),
                    },
                },
            },
        ],
    },
    fields => [qw/ name distribution date version maturity author /],
});

my $data = $releases->next->{data};
p $data;
```

**Comment by oalders** [comment]
I'm seeing a name and distribution here: https://explorer.metacpan.org/?url=%2Frelease%2FHMBRAND%2FDBD-CSV-0.24_02

**Comment by akarelas** [comment]
Another release having the same issue is archive = "Log-Reproducible-v0.12.1_a.tar_gz", date = "2014-10-19T03:04:08"

Replace the my $min_dt in the above script with:

```perl
my $min_dt = DateTime->new(
    year      => 2014,
    month     => 10,
    day       => 19,
    hour      => 3,
    minute    => 4,
    time_zone => 'UTC',
);
```

Prints:
```
{
    author     "COVINGTON",
    date       "2014-10-19T03:04:08" (dualvar: 2014),
    maturity   "released",
    version    "v0.12.1"
}
```

**Comment by akarelas** [comment]
So the problem is not that the release doesn't have a distribution and a name, but that those fields are somehow not returned by the search.

**Comment by mickeyn** [comment]
No. you are both looking at different records. note the file extension in the 'archive' field is different - 
one is 'tgz' and the other 'tbz'. The 'tbz' record seems to be missing some fields, not sure why (bad upload?).

**Comment by akarelas** [comment]
Those were the only two releases I found with this issue, after having searched through the entire date range.
