### ISSUE TITLE
Allow CircleCI config to check out a forked pull request

### ISSUE THREAD

**Issue by oalders** [metacpan/metacpan-api#1072]
This line does not appear to do the trick:

https://github.com/metacpan/metacpan-api/blob/37f2b5ce05d7382f9a71ce5821c84d269c6fe065/.circleci/config.yml#L32-L36

@2shortplanks any tips? 

The error is:

```
#!/bin/bash -eo pipefail
pushd metacpan-docker/src/metacpan-api
git checkout ${CIRCLE_BRANCH}

~/project/metacpan-docker/src/metacpan-api ~/project
error: pathspec 'pull/1071/head' did not match any file(s) known to git

Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by bombsimon** [comment]
Is the option to [build pull requests from forked repositories](https://circleci.com/docs/oss/#build-pull-requests-from-forked-repositories) enabled for this project? I never used CircleCI so not sure if this is relevant but I assume it has to be enabled either way.

**Comment by oalders** [comment]
It is. I think we got some good help here: https://twitter.com/metacpan/status/1585277450296201219 Just need to tweak the config.
