### ISSUE TITLE
Searching for releases of File::Glob and a few others returns no results

### ISSUE THREAD

**Issue by briandfoy** [metacpan/metacpan-api#1078]
I'm trying to track down an issue with CPAN::Audit (https://github.com/briandfoy/cpan-audit/issues/23#issuecomment-1296338713), and I suspect there may be some issues on the MetaCPAN API data side. Maybe there is or maybe CPAN::Audit is just doing it wrong. 

CPAN::Audit works by digesting a bunch of static files with info about module vulnerabilities, then combines that with information it extracts from the MetaCPAN API for each module. In this issue, CPAN::Audit fetches the list of all releases of a particular distro. This has been fine until recently, but now a small number of modules apparently have no release data in the API. 

For example, File::Glob used to return some hits and now doesn't. The release dropdown on MetaCPAN is a bit weird because it's the perl releases instead of the File::Glob versions, so I think you have some other things going on there so it's not the same code path:

```
$ curl -X POST http://fastapi.metacpan.org/v1/release/_search -H 'Content-Type: application/json' -d '{"size":5000,"fields":["date","version"],"filter":{"term":{"distribution": "File-Glob"}}}'
{
   "_shards" : {
      "total" : 3,
      "failed" : 0,
      "successful" : 3
   },
   "timed_out" : false,
   "hits" : {
      "hits" : [],
      "total" : 0,
      "max_score" : null
   },
   "took" : 10
}
```

Leaving out the fields doesn't help:

```
$ curl -X POST http://fastapi.metacpan.org/v1/release/_search -H 'Content-Type: application/json' -d '{"size":5000,"filter":{"term":{"distribution": "File-Glob"}}}'
{
   "timed_out" : false,
   "took" : 55,
   "hits" : {
      "max_score" : null,
      "total" : 0,
      "hits" : []
   },
   "_shards" : {
      "successful" : 3,
      "total" : 3,
      "failed" : 0
   }
}
```

[File::Fetch](https://metacpan.org/pod/File::Fetch), another core module, returns hits as expected.

```
$ curl -X POST http://fastapi.metacpan.org/v1/release/_search -H 'Content-Type: application/json' -d '{"size":5000,"fields":["date","version"],"filter":{"term":{"distribution": "File-Fetch"}}}'
```

There are about ten other distros that have the same problem and those aren't dual-lived or core modules (some are weird cases though), so I don't think core is the problem (but who knows?). For example, [Spoon::Cookie](https://metacpan.org/pod/Spoon::Cookie) shows the releases in the dropdown on MetaCPAN, but not in the API:

```
$ curl -X POST http://fastapi.metacpan.org/v1/release/_search -H 'Content-Type: application/json' -d '{"size":5000,"fields":["date","version"],"filter":{"term":{"distribution": "Spoon-Cookie"}}}'
{
   "timed_out" : false,
   "hits" : {
      "total" : 0,
      "max_score" : null,
      "hits" : []
   },
   "took" : 12,
   "_shards" : {
      "successful" : 3,
      "total" : 3,
      "failed" : 0
   }
}
```

**Comment by mickeyn** [comment]
From a (very) quick check I don't see a distribution named `File-Glob` (or a file in the CPAN directory) but a module named `File::Glob` which is part of the `perl` distribution.
Pretty sure that has something to do with the empty results, will take a closer look a bit later.

**Comment by haarg** [comment]
File::Glob is a core-only module. It has never been in its own distribution.

File::Fetch is a dual-life CPAN-first module. It is part of the [File-Fetch](https://metacpan.org/dist/File-Fetch) distribution.

Spoon::Cookie is part of the [Spoon](https://metacpan.org/dist/Spoon) distribution.

Distributions are based on the names of the tarballs uploaded to CPAN. You can't convert an arbitrary module name to a distribution with `s/::/-/g` and have it always exist on CPAN.

**Comment by briandfoy** [comment]
@haarg - this worked up until a couple months ago with File::Glob. I don't know what changed.

**Comment by haarg** [comment]
I don't know what to tell you. There was never a dist called `File-Glob`. Nothing is missing from MetaCPAN's index.

**Comment by Grinnz** [comment]
If you want to find the currently indexed release that provides a module, use the module endpoint with the module name (e.g. https://fastapi.metacpan.org/v1/module/File::Glob) and look at the release attribute returned. Note that distribution name on its own doesn't mean much and is not unique, whille the release name is a unique combination of distribution name and version (the filename without the extension).
