### ISSUE TITLE
App::Yabsm not being detected by MetaCPAN after changing version scheme

### ISSUE THREAD

**Issue by NicholasBHubbard** [metacpan/metacpan-api#1085]
I changed the versioning scheme of App::Yabsm from `MAJOR.MINOR` to `MAJOR.MINOR.PATCH`. Specifically I jumped from version `3.14` to `3.15.0`. This seemed to cause problems in MetaCPAN detecting the latest version, as it still thought that `3.14` was the newest version. For this reason I backpanned the old versions of App::Yabsm leaving only the newest one, in hopes that this would fix the problem. Unfortunately now it seems that App::Yabsm is not being detected at all by MetaCPAN.

Here is a MetaCPAN search for App::Yabsm: https://metacpan.org/search?size=20&q=App%3A%3AYabsm. This url gives me a page that says "No search results for App::Yabsm".

I also get "Not found" from this url: https://metacpan.org/dist/App-Yabsm.

However, I know that the latest version App::Yabsm (`3.15.1`) still exists on CPAN, and can be seen in my author directory from this url: http://www.cpan.org/authors/id/N/NH/NHUBBARD/

Please let me know if there is anyway I can help to resolve this.

**Comment by Grinnz** [comment]
3.15.0 is a lower version than 3.14, because the second decimal point causes the version to be interpreted as the other of Perl's two version schemes. See https://blogs.perl.org/users/grinnz/2018/04/a-guide-to-versions-in-perl.html for details, but essentially:

3.15.0 == 3.015
3.14 == 3.140.0

It's recommended to bump the major version whenever switching between the two version schemes to avoid confusion.

**Comment by Grinnz** [comment]
Also for the immediate question, queue the older version of the distribution for indexing on pause.perl.org, though uploading a new higher version would probably be a quicker fix.

**Comment by Grinnz** [comment]
No, that is the only way to trigger a reindex. But I meant to reindex 3.14 as that is the highest version you have currently uploaded.

**Comment by NicholasBHubbard** [comment]
Do you have any thoughts on what I should do?

**Comment by Grinnz** [comment]
You will need to upload a version that PAUSE and CPAN clients will recognize as higher. Did you get an email about the indexer run?

**Comment by oalders** [comment]
https://xdg.me/version-numbers-should-be-boring/

**Comment by Grinnz** [comment]
> It would be very unfortunate if I had to change the major version of my software. I would only do this if it were certain there is no other way to resolve this problem.

It is a suggestion to avoid making mistakes. You can simply release a higher version such as 3.150.0.

**Comment by Grinnz** [comment]
Or continue to use the decimal number version format.

**Comment by NicholasBHubbard** [comment]
I uploaded App::Yabsm version `3.150.0` about 30 hours ago. Unfortunately, it seems that it is still not being indexed as the links I shared still say that it cannot be not found.

Further, I forced a reindexing for this new version and got the same message I got when I tried to re-index `3.15.1` saying that it had never been indexed.

Here is the email I got for uploading the new version:

```
The uploaded file

    App-Yabsm-3.150.0.tar.gz

has entered CPAN as

  file: $CPAN/authors/id/N/NH/NHUBBARD/App-Yabsm-3.150.0.tar.gz
  size: 262428 bytes
sha256: e3d7f6a255554129cb57a72b971ff29074e0ca1d28f1282fa4716b533f43ba4c

CPAN Testers will start reporting results in an hour or so:

  http://matrix.cpantesters.org/?dist=App-Yabsm

Request entered by: NHUBBARD (Nicholas Hubbard)
Request entered on: Fri, 14 Apr 2023 11:25:13 GMT
Request completed:  Fri, 14 Apr 2023 11:26:12 GMT

Thanks,
-- 
paused, v1049
```
And here is the message I got when I forced a re-index:
```
According to a request entered by Nicholas Hubbard the
following files have been scheduled for reindexing.

WARNING: N/NH/NHUBBARD/App-Yabsm-3.150.0.meta has never been indexed.
(Maybe it's not a stable release and will not get (re)indexed.)
$CPAN/authors/id/N/NH/NHUBBARD/App-Yabsm-3.150.0.tar.gz


Estimated time of job completion: Sat Apr 15 19:02:00 2023 UTC

Thanks,
--
The PAUSE
```

**Comment by Grinnz** [comment]
Your distribution does not contain any module name App::Yabsm to index.

**Comment by Grinnz** [comment]
your last upload can be found here: https://metacpan.org/release/NHUBBARD/App-Yabsm-3.150.0

**Comment by NicholasBHubbard** [comment]
Ahh, I see. All of the modules are fatpacked into a single executable script. Ill have to figure out what I want to do.
