### ISSUE TITLE
Result is returned with content-type `text/html`

### ISSUE THREAD

**Issue by jackdeguest** [metacpan/metacpan-api#1111]
In the [versions endpoint](https://github.com/metacpan/metacpan-api/blob/97b4791bf274bfb4e25f3a122e7115a2e9315404/lib/MetaCPAN/Server/Controller/Release.pm#L95
) [`/v1/release/versions`](https://fastapi.metacpan.org/v1/release/versions/Module-Generic?versions=v0.30.5,v0.31.0&plain=1), when enabling the option `plain`, the data are returned as plain text, but the HTP response header has `Content-Type` set to `text/html`

**Comment by oalders** [comment]
I guess we just need to set `$res->content_type` here?
