### ISSUE TITLE
Wrong order of arguments for method `all_by_author`

### ISSUE THREAD

**Issue by jackdeguest** [metacpan/metacpan-api#1126]
In the code [here](https://github.com/metacpan/metacpan-api/blob/d87b27522e6584fcd3fb0eacea8f0b0745633d07/lib/MetaCPAN/Server/Controller/Release.pm#L82)

    my @params = @{ $c->req->params }{qw( page page_size )};

the arguments should actually be `page_size` then `page` based on the code [here](https://github.com/metacpan/metacpan-api/blob/d87b27522e6584fcd3fb0eacea8f0b0745633d07/lib/MetaCPAN/Query/Release.pm#L532)

    sub all_by_author {
        my ( $self, $author, $size, $page ) = @_;

**Comment by oalders** [comment]
Another great find, @jackdeguest. 😄

**Comment by oalders** [comment]
Closed via #1128

**Comment by jackdeguest** [comment]
Since this fix has been reverted on September 8th, is there any plan to re-introduce it again?

**Comment by mickeyn** [comment]
The change caused an issue with metacpan-web links. To reintroduce it, we need to investigate why the links sent from metacpan-web have reversed params.
This will require some time on my part, help is appreciated.

**Comment by jackdeguest** [comment]
> The change caused an issue with metacpan-web links. To reintroduce it, we need to investigate why the links sent from metacpan-web have reversed params.
> This will require some time on my part, help is appreciated.

I would be happy to help you, but I know nothing of the system. This might be a steep learning curve, no ?
However, I have a knack for troubleshooting, so maybe I can look at the code and investigate...

**Comment by mickeyn** [comment]
yeah, the wrong order is indeed on the metacpan-web side. I'll create a fix there.

**Comment by mickeyn** [comment]
https://github.com/metacpan/metacpan-web/pull/2939 will fix that

**Comment by jackdeguest** [comment]
> yeah, the wrong order is indeed on the metacpan-web side. I'll create a fix there.

Thank you so much @mickeyn for your time and your work ! Much appreciate it.

**Comment by oalders** [comment]
Thanks @jackdeguest and @mickeyn!
