### ISSUE TITLE
Field 'maturity' in /release/recent API end point

### ISSUE THREAD

**Issue by michal-josef-spacek** [metacpan/metacpan-api#1146]
For change https://github.com/metacpan/metacpan-web/issues/2954 I need to add maturity field to /release/recent API end point.

Is it feasible?

I could implement it.

**Comment by mickeyn** [comment]
created a PR

**Comment by oalders** [comment]
Closed via #1146. @michal-josef-spacek, please let us know if you need anything else. Not sure when the API will start serving this new field. @mickeyn?

**Comment by michal-josef-spacek** [comment]
Thank you very much, it's working well.
