### ISSUE TITLE
Search should support the right spelling, regardless of if the user is British.

### ISSUE THREAD

**Issue by EvanCarroll** [metacpan/metacpan-api#1223]
I just tried searching for  `Types::Serializer` and I got nothing. Moreover, [all the results are pretty bad](https://metacpan.org/search?size=20&q=types%3A%3Aserializer).

The spelling of the module is currently `Types::Serialiser`.. with an `s`. I would think we should handle this better.

**Comment by EvanCarroll** [comment]
I don't use Elastic Search. It's not cryptic feedback. If you search for the American spelling, you get unrelated results. That's pretty direct. It's not cryptic because I don't know Elastic Search. But sure, I'll ask the question...

https://dba.stackexchange.com/questions/339652/how-can-you-handle-internationalized-queries-with-elastic-search

**Comment by mickeyn** [comment]
Thanks for clarifying. 
What I meant by cryptic is that I can't work with "all the results are pretty bad", that's not very actionable. 
We are currently working to upgrade the Elastic Search version of MetaCPAN and hopefully the newer versions produce more accurate results, in the meantime - there's nothing we can do with the names of files in CPAN (as I said, that's something to take with the owners who upload them).
