### ISSUE TITLE
Index fails on bad META provides

### ISSUE THREAD

**Issue by grantm** [metacpan/metacpan-api#218]
I noticed these two releases failed to index on my dev instance and aren't on metacpan either:

```
authors/id/B/BA/BARBIE/CPAN-Testers-WWW-Statistics-1.00.tar.gz
authors/id/M/MU/MUGENKEN/Helper-Commit-0.000004.tar.gz
```

In each case, the indexer failed with the error:

```
Can't call method "add_module" on an undefined value at lib/MetaCPAN/Script/Release.pm line 295.
```

Looking at the code and the distributions tarballs, it appears that in each case there's a file listed in the 'provides' section of the META.json which doesn't actually exist in the tarball.

This probably shouldn't be a fatal error causing the release to not be indexed.

**Comment by ranguard** [comment]
CPAN::Testers is now indexed - and Helper Commit isn't in s.c.o either
