### ISSUE TITLE
"Raw" access to images delivered as MIME="text/plain" instead of "image/png"

### ISSUE THREAD

**Issue by kentfredric** [metacpan/metacpan-api#272]
If you look in the file listing for http://api.metacpan.org/source/KENTNL/MetaPOD-0.1.3/examples/ , you'll see it clearly knows the MIME type of the images in that dir:

``` text
Name    Size    Type    Last Modified
Parent Directory            
self_structure.dot  725 application/msword  Sun, 02 Jun 2013 08:28:08 GMT
self_structure.pl   859 text/x-script.perl  Sun, 02 Jun 2013 08:28:08 GMT
self_structure.png  27951   image/png   Sun, 02 Jun 2013 08:28:08 GMT
```

However, if you view the `png` file

http://api.metacpan.org/source/KENTNL/MetaPOD-0.1.3/examples/self_structure.png

It gets dispatched as `text/plain`

Which is not very useful.

**Comment by haarg** [comment]
We should set X-Content-Type-Options: nosniff to prevent the files from being misused, which would prevent Chrome from displaying the image even when we are giving a different content type.
