### ISSUE TITLE
Provide checksums for files in download_url (of distribution)

### ISSUE THREAD

**Issue by rehsack** [metacpan/metacpan-api#327]
Please add support for fetching checksums via MetaCPAN API to allow verification of downloaded sources. Interesting checksums are for SHA1 and RDN160 for Pkgsrc and MD5 and SHA256 for Yocto. Generally it would be cool when the checksum method could be specified and metacpan.org could use an own mirror for on-the-fly generation.

**Comment by mikroskeem** [comment]
Any updates on this?

**Comment by oalders** [comment]
Looks like this is just waiting for a volunteer?  I think it would be a great feature to have.  I read this the other day and it had me thinking more about checksums: https://blog.golang.org/modules2019

**Comment by oalders** [comment]
Closed via #883.  Thanks @mickeyn!
