### ISSUE TITLE
Wrong Version Listed for Number-Phone

### ISSUE THREAD

**Issue by theory** [metacpan/metacpan-api#364]
For some reason, http://api.metacpan.org/v0/release/Number-Phone says the current release is 2.1, but [it’s actually 3.0004](http://search.cpan.org/dist/Number-Phone/). Seems to have changed in the last 25 hours, as my daily [rpmcpan](https://github.com/iovation/rpmcpan) cron job just started dying on this issue an hour ago

**Comment by rwstauner** [comment]
FTR I posed similar questions to the mailing list:
http://www.mail-archive.com/pod-people@perl.org/msg01712.html
