### ISSUE TITLE
[mi/es2] investigate use of suggester

### ISSUE THREAD

**Issue by mickeyn** [metacpan/metacpan-api#470]
see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html
as an optional alternative to our current `autocomplete` query

**Comment by jberger** [comment]
Implemented via https://github.com/metacpan/metacpan-api/pull/764 and https://github.com/metacpan/metacpan-web/pull/1992

**Comment by jberger** [comment]
And now note that we are changing the structure to include more information: https://github.com/metacpan/metacpan-api/pull/768
