### ISSUE TITLE
download_url QA. (was: "module" search is too restrictive?)

### ISSUE THREAD

**Issue by karenetheridge** [metacpan/metacpan-api#483]
from #metacpan on May 16:

16:00 < ether> I'm not sure if this is a perlbrew or metacpan issue -- are the search args being passed here correct?   https://github.com/miyagawa/cpanminus/issues/501
16:01 < ether> if 'path' => 'module' is wrong, what should it be instead?

**Comment by oalders** [comment]
Sadly, I don't think there's a quick fix here.  Having said that, v1 does have an endpoint which was built specifically for `cpanm`: https://github.com/CPAN-API/cpan-api/blob/mi/es2/lib/MetaCPAN/Document/File/Set.pm#L110

I think it still needs some testing, but this was done by @clintongormley to deal specifically with the needs of that client.

**Comment by clintongormley** [comment]
Yeah I couldn't figure out how to build a version of metacpan containing the docs I needed for testing, but that API seemed to do the right thing if I remember correctly.

@miyagawa may be able to provide the relevant test cases.

Importantly, the `find_download_url` is much more efficient than a number of other metacpan queries because it uses `nested` queries to decide which docs to return, while in other places in metacpan, all possible matching docs are returned then whittled down with perl code.

@karenetheridge I don't really understand what this means

> The wrong module/distribution is found when searching in --dev mode, when a .pod module supercedes a .pm.

but if we could understand the logic that needs to be applied (based on the fields available in metacpan) then possibly we could rejig the query to make it work

**Comment by ranguard** [comment]
V1 (under heavy development, which includes us re-indexing everything sometime) is available at: https://api-v1.metacpan.org/ e.g. https://api-v1.metacpan.org/author/ - if anyone wants to play

**Comment by karenetheridge** [comment]
> @karenetheridge I don't really understand what this means
>
> >    The wrong module/distribution is found when searching in --dev mode, when a .pod module supercedes a .pm.

What's happening here is:

* cpanm --dev is doing a module search for Moose::Cookbook::Legacy::Debugging_BaseClassReplacement, and gets a result of DOY/Moose-2.0604.tar.gz
* it is actually in the 02packages index pointing to the most recent Moose release, ETHER/2.1801! so that is the distribution that should be returned.
* 2.0604 is the last Moose release where that module was a .pm file; in subsequent releases it became a .pod file -- therefore the search is too restrictive; it should be as inclusive as the PAUSE index itself is (which respects .pod files)

**Comment by karenetheridge** [comment]
Here is another example of a similar query failure (the wrong distribution is found for the module 'encoding'):

    $ cpanm --dev encoding
    --> Working on encoding
    Fetching http://mirrors.gossamer-threads.com/CPAN/authors/id/D/DA/DANKOGAI/Encode-2.48.tar.gz ... OK
    Configuring Encode-2.48 ... OK
    Building and testing Encode-2.48 ... ^C

    $ grep encoding ~/.cpanm/02packages.details.txt
    encoding                           2.17  D/DA/DANKOGAI/Encode-2.84.tar.gz

**Comment by karenetheridge** [comment]
Here's another bizarre bad result:

```
$ cpanm --dev Module::Install::Base::FakeAdmin
--> Working on Module::Install::Base::FakeAdmin
Fetching http://www.cpan.org/authors/id/A/AU/AUTRIJUS/Language-Haskell-0.01.tar.gz ... OK
Configuring Language-Haskell-0.01 ... OK
Building and testing Language-Haskell-0.01 ... FAIL
```

Module::Install::Base::FakeAdmin is indexed to the Module-Install distribution. Why is it coming back with AUTRIJUS/Language-Haskell-0.01.tar.gz ?!

**Comment by karenetheridge** [comment]
woohoo, https://api-v1.metacpan.org/module/Moose::Cookbook::Legacy::Debugging_BaseClassReplacement

returns:

```
{
...
   "path" : "lib/Moose/Cookbook/Legacy/Debugging_BaseClassReplacement.pod",
   "download_url" : "https://cpan.metacpan.org/authors/id/E/ET/ETHER/Moose-2.1804.tar.gz",
...
}
```

**Comment by karenetheridge** [comment]
However, this is still a bad result:

https://api-v1.metacpan.org/module/Module::Install::Base::FakeAdmin

```
{
   "download_url" : "https://cpan.metacpan.org/authors/id/A/AU/AUTRIJUS/Language-Haskell-0.01.tar.gz",
...
}
```

**Comment by oalders** [comment]
@karenetheridge This is @clintongormley's new endpoint.  We should include that in this discussion.

 https://api-v1.metacpan.org/download_url/Module::Install::Base::FakeAdmin

```
{
   "date" : "2015-05-02T01:06:38",
   "status" : "latest",
   "version" : "0",
   "download_url" : "https://cpan.metacpan.org/authors/id/E/ET/ETHER/Module-Install-1.16.tar.gz"
}
```

https://api-v1.metacpan.org/download_url/Moose::Cookbook::Legacy::Debugging_BaseClassReplacement

```
{
   "download_url" : "https://cpan.metacpan.org/authors/id/E/ET/ETHER/Moose-2.0802.tar.gz",
   "version" : "2.0802",
   "status" : "cpan",
   "date" : "2013-05-07T17:10:09"
}
```

**Comment by karenetheridge** [comment]
@oalders bizarre! of those two searches, now Module::Install::Base::FakeAdmin is correct and Moose::Cookbook::Legacy::Debugging_BaseClassReplacement is wrong :)

**Comment by oalders** [comment]
:)

We should make sure this is correct before migrating officially to v1.  For anyone who wants to hack on this, the relevant code is at https://github.com/CPAN-API/cpan-api/blob/master/lib/MetaCPAN/Document/File/Set.pm#L17

**Comment by clintongormley** [comment]
@oalders Sorry I don't have the time to delve into this in detail, but if you need any help with specific Elasticsearch queries (eg I need to change the logic to do X) I'm happy to help.

**Comment by clintongormley** [comment]
btw the blocker for me with this endpoint was that I couldn't figure out how to write the tests

**Comment by skaji** [comment]
(From IRC...)
I'm currently trying to move over cpanminus MetaCPAN client to v1.

https://api-v1.metacpan.org/download_url/Net::LDAP::Server::Test?version=%3D%3D%200.14
(here the version query is "== 0.14") returns "status cpan" but I think it should be "status backpan".

In fact,
http://www.cpan.org/authors/id/K/KA/KARMAN/Net-LDAP-Server-Test-0.14.tar.gz returns 404 Not Found
http://backpan.perl.org/authors/id/K/KA/KARMAN/Net-LDAP-Server-Test-0.14.tar.gz returns 200 OK

Note: cpanminus has a test for backpan search
https://github.com/miyagawa/cpanminus/blob/menlo/xt/cli/backpan_search.t#L5-L8

**Comment by skaji** [comment]
Another issue related backpan:
backpan should be excluded when searching dev releases.
https://github.com/CPAN-API/cpan-api/blob/master/lib/MetaCPAN/Document/File/Set.pm#L158

But actually https://api-v1.metacpan.org/download_url/Test::Simple?dev=1 returns
```
{
   "date" : "2011-02-28T13:00:05",
   "version" : "2.00_07",
   "download_url" : "https://cpan.metacpan.org/authors/id/M/MS/MSCHWERN/Test-Simple-2.00_07.tar.gz",
   "status" : "cpan"
}
```
here 2.00_07 is in backpan.

Please let me know when I should open a new issue.

**Comment by skaji** [comment]
FYI: Now
https://fastapi.metacpan.org/v1/download_url/Net::LDAP::Server::Test?version=%3D%3D%200.14 returns `status backpan`, and
https://fastapi.metacpan.org/v1/download_url/Test::Simple?dev=1 returns a distribution which is not in backpan 👍

**Comment by mickeyn** [comment]
@skaji I was doing some status cleanups/updates during the weekend, they were a bit off compared to v0. hope they are good now.

**Comment by skaji** [comment]
Let's go back to @karenetheridge's original issue.

#### (a) encoding -> solved

* D/DA/DANKOGAI/Encode-2.84.tar.gz has encoding 2.17   (== 2.170)
* D/DA/DANKOGAI/Encode-2.48.tar.gz has encoding 2.6_01 (== 2.601)

So it is correct that dev search of MetaCPAN v0 (and `cpanm --dev encoding`) returns  Encode-2.48.


#### (b) Module::Install::Base::FakeAdmin -> solved

Now MetaCPAN v1 returns Module-Install. http://fastapi.metacpan.org/v1/download_url/Module::Install::Base::FakeAdmin?dev=1 
http://fastapi.metacpan.org/v1/download_url/Module::Install::Base::FakeAdmin

#### (c) Moose::Cookbook::Legacy::Debugging_BaseClassReplacement (=MCLD) -> NOT SOLVED

* Moose-2.1804 has MCLD.pod, and META.json "provides" declares its version is 2.1804  
https://metacpan.org/source/ETHER/Moose-2.1804/META.json#L380
* Moose-2.0604 has MCLD.pm with version 2.0604  
https://metacpan.org/source/DOY/Moose-2.0604/lib/Moose/Cookbook/Legacy/Debugging_BaseClassReplacement.pm#L6
* MetaCPAN returns 2.0604  
https://fastapi.metacpan.org/v1/download_url/Moose::Cookbook::Legacy::Debugging_BaseClassReplacement
* PAUSE (02packages.details.txt) returns 2.1804  
http://www.cpan.org/modules/02packages.details.txt

So It seems that MetaCPAN does not count META.json correctly.
We could refer to [Parse::LocalDistribution](https://metacpan.org/pod/Parse::LocalDistribution) for how PAUSE parses distributions.

**Comment by skaji** [comment]
I found another issue related `!=` notation.

https://fastapi.metacpan.org/v1/download_url/Moose?version=!%3D+2.1805
expect: 200 OK, Moose with version 2.1804
actual: 500 Internal Server Error

cf https://gist.github.com/skaji/f08b71f44866c0951fec460b3e2730df

**Comment by haarg** [comment]
The issues with Moose's pod files is #336

**Comment by oalders** [comment]
This looks good on our end.  @skaji could you open a new ticket if you find anything else?
