### ISSUE TITLE
incorrect ordering of results between .pod and .pm files

### ISSUE THREAD

**Issue by karenetheridge** [metacpan/metacpan-api#491]
I searched for "Apache2::SizeLimit" -- the top two results were:
- https://metacpan.org/pod/distribution/mod_perl/docs/api/Apache2/SizeLimit.pod in https://metacpan.org/release/mod_perl
- https://metacpan.org/pod/Apache2::SizeLimit in https://metacpan.org/release/Apache-SizeLimit

The second result should come first, because:
1. the PAUSE index points to Apache2::SizeLimit being found in the Apache-SizeLimit distribution
2. the mod_perl distribution only contains pod; the Apache-SizeLimit distribution contains both the .pm code _and_ pod (in the same file).

**Comment by mickeyn** [comment]
seems reversed now (both v0 & v1) - can you please verify and close the issue?

**Comment by karenetheridge** [comment]
Negative -- https://metacpan.org/search?q=apache2%3A%3Asizelimit&search_type=authors still returns mod_perl as the first result.

**Comment by mickeyn** [comment]
Oh, I see. I copy-pasted the search term you wrote - with the capitalized words and *that* works.
When it's all lower-cased ES gives the reverse results.
We'll have to look into the scoring algorithm.

**Comment by jberger** [comment]
When I look at @karenetheridge 's query now it seems to give the proper (non mod_perl) result as the top on both v0 and v1 now. Has this resolved itself somehow?
