### ISSUE TITLE
Include number of {BackPAN,CPAN} {releases,distributions} on authors

### ISSUE THREAD

**Issue by neilb** [metacpan/metacpan-api#502]
It would be handy if we could add the following information to authors:

 * number of distributions the author has on CPAN
 * number of distributions the author has on BackPAN

Then on the web interface, if an author has no distributions on CPAN, but has dists on BackPAN, then the author page could reflect that, instead of just saying "no releases" (that change to the web interface was suggested by @book in [metacpan-web #1692](https://github.com/metacpan/metacpan-web/issues/1692))

**Comment by mickeyn** [comment]
1. a distribution is not identified by an author, so let's stick to 'releases'.
2. do you want to aggregate the status 'latest' into 'cpan' or keep them separated?

my idea is to add to the author end-point (the API side) another key (we can choose another name), and the endpoint will return something like:
```
{
   "pauseid" : "NEILB",
   "name" : "Neil Bowers",
   ...
   "release_count": {
      "cpan": 87,
      "latest": 117,
      "backpan": 484
   }
}
```

WEB side changes can follow once this data is in the index & served through the author endpoint

**Comment by neilb** [comment]
@mickeyn with the following interpretations?

 * **latest** means they have that many releases that are the latest of the relevant distribution in their CPAN author directory
 * **cpan** means they have that many additional releases sitting in their author directory
 * **backpan** is the total number of releases in their BackPAN directory. So **backpan** includes **latest** and **cpan**.

**Comment by mickeyn** [comment]
A small correction: **backpan** (MetaCPAN's status=**backpan**) cannot include **latest** as it is built of the list of files not found in `CPAN/indices/find-ls.gz` - so for us that's a count of **`in BackPAN but not in CPAN`**.

**Comment by neilb** [comment]
Ah, right. So could we have **backpan-only** and **backpan-total** as two separate keys, which would make it clear? But if that would be a pain, then the three keys you listed would be handy anyway.

**Comment by mickeyn** [comment]
sure, but that means I aggregate the numbers of the 3 statuses we have to get **backpan-total** - it's not the real thing

**Comment by neilb** [comment]
yeah, could drop the total, but maybe change the **backpan** key to **backpan-only**, to make it clearer what it is?

**Comment by mickeyn** [comment]
sure

**Comment by neilb** [comment]
Cool. I like your proposal.

**Comment by mickeyn** [comment]
now that we have the numbers, do we want to change the wording of the
"No... were found" line (what would you suggest to write?) and/or show count match near the links?
something like -
![selection_020](https://cloud.githubusercontent.com/assets/3648710/16732190/2ce34f36-477c-11e6-93e9-730e8716a020.png)

**Comment by mickeyn** [comment]
poke @neilb

**Comment by neilb** [comment]
@mickeyn:

I like the idea of having the counts next to the links in the sidebar.

When there are no releases, instead of the current:

> No releases from AFOXSON could be found

How about the following?

> No releases from AFOXSON could be found.
> AFOXSON has [5 distributions on BackPAN](http://cpan.metacpan.org/authors/id/A/AF/AFOXSON/) that were previously on CPAN.

**Comment by mickeyn** [comment]
sound good

**Comment by mickeyn** [comment]
this is now done and liv: https://v1.metacpan.org/author/AFOXSON

**Comment by neilb** [comment]
:+1:

Thanks @mickeyn!

**Comment by mickeyn** [comment]
closing :)
