### ISSUE TITLE
API errors on live

### ISSUE THREAD

**Issue by ranguard** [metacpan/metacpan-api#503]
``` sh
cd /var/log/nginx/metacpan-api/
grep ' 500 ' access.log
```

62.143.88.21 23.235.40.47 - - [06/Jul/2016:20:30:46 +0100] "POST /author/ HTTP/1.1" 500 1262 "https://v1.metacpan.org/source/LEONT/ExtUtils-PL2Bat-0.001/lib/ExtUtils/PL2Bat.pm" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36" 499361 0.059 443 api-v1.metacpan.org 0.059

80.100.130.165 23.235.40.43 - - [06/Jul/2016:20:31:04 +0100] "DELETE /_search/scroll HTTP/1.1" 500 998 "-" "HTTP-Tiny/0.058" 499309 0.156 443 fastapi.metacpan.org 0.012

``` sh
cd /var/log/starman/metacpan-api
tail starman_error.log
```

Use of uninitialized value $_[0] in string at /home/metacpan/carton/metacpan-api/lib/perl5/Search/Elasticsearch/Util/API/QS.pm line 23, <$fh> line 1.

**Comment by mickeyn** [comment]
still relevant? seem like temporary issues, all 500s I see in the logs are for pages that are available now.

**Comment by tsibley** [comment]
`bzgrep ' 500 ' access.log access.log-2016{09,10,11}*` returns ~100 `GET /` requests which appear to come mostly from scanners.

**Comment by tsibley** [comment]
Ignore that.  lw-mc-01 and -02 aren't getting real traffic.  I'll look at lw-mc-03.

**Comment by tsibley** [comment]
Looking at traffic for fastapi.metacpan.org on lw-mc-03 for all of November, there are hundreds of thousands of POSTs to `/{file,favorite,rating,author,release}/_search` which are 500-ing from our LW hosts.  Presumably they're being made by our web backends.  The logs don't have visibility into the body of the POST, so it's hard to know from them alone what sort of requests we're looking at.

**Comment by tsibley** [comment]
The bulk of the `/file/_search` were from a web crawler triggering the edge case in #1792.

**Comment by tsibley** [comment]
I don't think it's worth looking into the other 500s (and other statuses) which are logged.  It's difficult to trace down the issues because the meaningful information is in the POST body, which isn't easily accessible.  The /var/log/elasticsearch/es-01/bm.log is useful, but only if you know the timestamp.  It's also non-trivial to separate out bugs in the metacpan code vs. random users' queries.
