### ISSUE TITLE
CPAN-Meta-Check and CGI-Emulate-PSGI Missing from the New API

### ISSUE THREAD

**Issue by theory** [metacpan/metacpan-api#518]
A v1 API request for [release/CPAN-Meta-Check](https://fastapi.metacpan.org/release/CPAN-Meta-Check) returns a 404. However, it does exist in the [v0 site](https://metacpan.org/release/CPAN-Meta-Check).

A v1 API request for [release/CGI-Emulate-PSGI](https://fastapi.metacpan.org/release/CGI-Emulate-PSGI) returns a 404. However, it does exist in the [v0 site](https://metacpan.org/release/CGI-Emulate-PSGI).

**Comment by mickeyn** [comment]
fixed
