### ISSUE TITLE
V1 API does not support 'source' queries

### ISSUE THREAD

**Issue by TiMBuS** [metacpan/metacpan-api#522]
cpanm uses 'source' queries to avoid POST requests (for whatever reason). 
See the *Note* section here for an example: https://github.com/metacpan/metacpan-api/blob/master/docs/API-docs.md#user-content-downstream-dependencies

Running the linked example curl request against fastapi.metacpan.org/v1/ throws this error:
```
{
   "message" : "[Param] ** Unknown param (source) in (search) request. See docs at: http://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html, called from sub Search::Elasticsearch::Role::Client::Direct::__ANON__ at /home/metacpan/metacpan-api/lib/MetaCPAN/Server/Controller.pm line 110."
}
```
Which sadly breaks cpanm/menlo.

**Comment by skaji** [comment]
I think cpanm will use download_url endpoint.

**Comment by TiMBuS** [comment]
From what I can see, Menlo tries the following query first:

```json
localhost:5000/file/_search?source={
  "fields": [
    "date",
    "release",
    "author",
    "module",
    "status"
  ],
  "query": {
    "filtered": {
      "query": {
        "nested": {
          "path": "module",
          "score_mode": "max",
          "query": {
            "custom_score": {
              "query": {
                "constant_score": {
                  "filter": {
                    "and": [
                      {
                        "term": {
                          "module.authorized": true
                        }
                      },
                      {
                        "term": {
                          "module.indexed": true
                        }
                      },
                      {
                        "term": {
                          "module.name": "TestModule"
                        }
                      }
                    ]
                  }
                }
              },
              "metacpan_script": "score_version_numified"
            }
          }
        }
      },
      "filter": {
        "and": [
          {
            "term": {
              "maturity": "released"
            }
          }
        ]
      }
    }
  }
}
```

It will then query `release/_search?source={{release & author}}` and finally fish out the download_url. This would all still work if 'source' was working.

**Comment by mickeyn** [comment]
@TiMBuS maybe I misunderstood, but you can't expect ES queries for v0 (ES0.20) to simply work on v1 (ES2.3)

**Comment by ranguard** [comment]
@mickeyn @TiMBuS is playing with our interface.

@TiMBuS please use our `legacy/v0` branches (for puppet web and api) if you do not want to play with the new version of ES, but we no longer support this. At the same time not all the tools have caught up with our v1 (what is currently on master), which we haven't deployed to production yet as it's still under heavy development.

I know we are building/fixing the `download_url` for `cpanm` and others, so they don't have to have ES code in them at all (means going forward we can fix things without everyone having to download a new version of `cpanm` for example.

Hope that helps!

**Comment by mickeyn** [comment]
@TiMBuS can you test with my branch?

**Comment by TiMBuS** [comment]
@ranguard understood that the v1 API works differently, @oalders had already informed me about this on IRC, but also encouraged me to create this issue.

@mickeyn Unfortunately it is the weekend in Australia and I don't have my work laptop with me to test this without setting up the whole vagrant image again.. I can test it on my Monday if you really need confirmation before merging but if it works for you with the above GET request then I am very sure that your fix is good.

**Comment by mickeyn** [comment]
@TiMBuS ok, we'll merge it.
sending the query through 'source' over a GET request will work, though your specific query syntax needs to be fixed to work with ES 2 (you'll get a query parsing error from ES).

**Comment by TiMBuS** [comment]
Awesome, looks workable to me (ignoring that I could have just changed my cpanm to use a POST). 

Thanks a lot @mickeyn :)
