### ISSUE TITLE
A specific release doesn't have a distribution field in elasticsearch

### ISSUE THREAD

**Issue by akarelas** [metacpan/metacpan-api#528]
This release BIGREDS/Mail-Postfixadmin-0.201306233
doesn't return a distribution field when queried on elasticsearch
metacpan v0

I suppose it doesn't have a distribution field.

**Comment by mickeyn** [comment]
I guess this is related to https://github.com/metacpan/metacpan-web/issues/1773

did you try querying it on v1?

**Comment by akarelas** [comment]
No, I didn't try. Would you like to? I don't know how ES2 works (whether the JSON body has to be the same or different). Sorry.

**Comment by mickeyn** [comment]
it's OK on v1 (that's also why it appears correctly on the list in https://github.com/metacpan/metacpan-web/issues/1773).
closing.
