### ISSUE TITLE
Always unarchive to the same location

### ISSUE THREAD

**Issue by oalders** [metacpan/metacpan-api#538]
Archives are unpacked to a different location than the source files that the API serves up. This means that we're actually keeping inflated 2 copies of most CPAN distributions, which is eating up a lot of space on disk. There should be 1 location that the API and the indexer look to for inflated archives. We can add an option to the indexer to wipe an archive out and then re-inflated it from scratch. By default, we should not bother inflating if the code already exists on disk.

**Comment by ranguard** [comment]
Indexing uses the scratch RAM disk, so don't think we need this any more?

**Comment by oalders** [comment]
Works for me!
