### ISSUE TITLE
backwards compatibility shim for cpanm

### ISSUE THREAD

**Issue by haarg** [metacpan/metacpan-api#539]
We should provide a shim that is backwards compatible with the v0 queries cpanm uses.

**Comment by ranguard** [comment]
@haarg has started this here: https://github.com/metacpan/metacpan-api-v0-shim

As we are now serving api.mc.org via fastly, we could detect the useragent and switch to a different backend (on our new infrastructure), so we are 100% sure cpanm clients are ALL getting the same data and taking advantage of our new setup.

This would be a good step in our depreciation cycle

**Comment by ranguard** [comment]
Done and live
