### ISSUE TITLE
Purge dists when we downgrade from latest to cpan

### ISSUE THREAD

**Issue by ranguard** [metacpan/metacpan-api#566]

**Comment by tsibley** [comment]
@ranguard Isn't this done already by https://github.com/metacpan/metacpan-api/blob/master/lib/MetaCPAN/Script/Release.pm#L189-L190?

**Comment by ranguard** [comment]
You mean https://github.com/metacpan/metacpan-api/blob/master/lib/MetaCPAN/Script/Latest.pm#L209  ? yea looks like it? - should have noted a test case I guess - but don't remember though and that line was before this issue was created!

Going to close for now as obviously not been that much of an issue!

**Comment by tsibley** [comment]
Yeah, that line.
