### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by oalders** [metacpan/metacpan-api#57]
Dists and modules should be taggable.  Perhaps authors as well.  There needs to be discussion on the UI and about standard and user-defined tags.

**Comment by cxw42** [comment]
metacpan/metacpan-web#452 refers here - I am increasingly interested in tagging.  For example, finding all static blogging packages via the web API is not trivial!

@ranguard Could you point me to the other issues you referred to?  I see #253, but the title of that issue doesn't clearly indicate that tagging is also part of the discussion.

Thanks!

**Comment by ranguard** [comment]
@cxw42 I think (It was almost 5 years ago!) I _was_ talking about #253 which was to be a recommendation system, that included some form of tagging as part of the solution and it was hoped that could open other uses...
