### ISSUE TITLE
add 'deprecated' field to release type

### ISSUE THREAD

**Issue by mickeyn** [metacpan/metacpan-api#572]
can be taken from the meta, let's add it to the release result as a query-able field 

It should also look at the POD `name` attribute and look for `DEPRECIATED`  or `DEPRECATED` (case sensitive)

**Comment by oalders** [comment]
I think we should add this field to modules as well.

**Comment by oalders** [comment]
See also https://github.com/metacpan/metacpan-web/issues/1435

**Comment by mickeyn** [comment]
This is now done, both `file` and `release` types have a `deprecated` field.
