### ISSUE TITLE
Get API clients to upgrade

### ISSUE THREAD

**Issue by ranguard** [metacpan/metacpan-api#573]
- cpanm
- cpm
- Menlo
- ????

**Comment by haarg** [comment]
miyagawa/cpanminus#522 cpanm
miyagawa/cpanminus#520 Menlo (unreviewed)

cpm appears to already be using the new api: https://github.com/skaji/cpm/blob/master/lib/App/cpm/Resolver/MetaCPAN.pm#L19

**Comment by ranguard** [comment]
@haarg maybe worth chasing those PRs then we can discuss at PTS?

**Comment by ranguard** [comment]
back compat shim now in place
