### ISSUE TITLE
v1 autocomplete queries don't filter _source

### ISSUE THREAD

**Issue by akarelas** [metacpan/metacpan-api#577]
When I type this in Metacpan api explorer ```/v1/search/autocomplete?q=Mojoli&fields=documentation``` I get an enormous output, because for each result item, I get its _source as well, which contains POD and description.

Can you please filter out _source?

**Comment by jberger** [comment]
@akarelas why does it matter? Surely having more data is better than less and other consumers might want the _source field.

**Comment by jberger** [comment]
I suppose the counter argument might be that autocomplete needs to be fast and probably is better to be lean.

**Comment by akarelas** [comment]
Big amounts of bandwidth gets spent with no reason. Also speed might be a concern. Maybe there could be an option, such as &_source=false
