### ISSUE TITLE
/pod exists /release/ does not for Class::Base

### ISSUE THREAD

**Issue by szabgab** [metacpan/metacpan-api#582]
https://metacpan.org/pod/Class::Base exists but clicking on Class-Base-0.08 in the breadcrumbs leads to https://metacpan.org/release/Class-Base which is "Not Found"

**Comment by haarg** [comment]
I've reindexed this dist to fix it, but there is still an issue with how we link things in cases like this.

**Comment by haarg** [comment]
The linking has been fixed with metacpan/metacpan-web#1828
