### ISSUE TITLE
libxml-enno Missing Prereqs

### ISSUE THREAD

**Issue by theory** [metacpan/metacpan-api#591]
The [libxml-enno release JSON](https://fastapi.metacpan.org/v1/release/libxml-enno) has no prereqs:

      "prereqs" : {},

This is an old distribution, admittedly, with no `META.(?:json|yml)`. Still, the [Makefile.PL](https://metacpan.org/source/ENNO/libxml-enno-1.02/Makefile.PL) has prereqs:

    WriteMakefile(
        NAME        => 'libxml-enno',
        VERSION_FROM => 'Makefile.PL',
        PREREQ_PM => { 'XML::Parser' => '2.19',
                       # Maybe requiring Date::Manip 5.33 is too strict,
                       # it's what I was using. I know 5.20 doesn't work.
                       # I also know that 5.36 works.
                       'Date::Manip' => '5.33', 
                       'Parse::Yapp' => '0',
                       # LWP::UserAgent is used when parsing XML from URLs
                       # It's part of libwww-perl, and you don't strictly need it
                       # (some test cases may fail)
                       'LWP::UserAgent' => '0',
                       # XML::Parser::PerlSAX is part of libxml-perl.
                       # It's used by some test cases in t/chk_batch.t and you 
                       # don't strictly need it. Version 0.05 causes errors in the
                       # test cases in t/chk_batch.t.
                       'XML::Parser::PerlSAX' => '0.07',
                       },
        dist        => {'COMPRESS'  => 'gzip', 'SUFFIX'    => '.gz'},
        EXE_FILES => [ 'bin/xql.pl' ],
    );

Is MetaCPAN unable to extract these?

**Comment by tsibley** [comment]
MetaCPAN only looks at the static metadata.  It doesn't try to parse the Makefile.PL and never even considers running it.

How many cases are there of old releases with no META file?  If it's large enough, I imagine we'd be open to a patch to statically parse the Makefile.PL/Build.PL as a "best effort" in the case of no META file.

**Comment by tsibley** [comment]
I'm going to close this for now as "champion required".  If someone wants to move such a thing forward, we can re-open it.

**Comment by theory** [comment]
Yeah, might be better served by someone taking on the distribution in question and modernizing its build stuff.

**Comment by tsibley** [comment]
Even just making a new release with the existing release code but a newer Perl toolchain would help as that should generate a META file.
