### ISSUE TITLE
No download_url for Term-Screen-Wizard

### ISSUE THREAD

**Issue by neilb** [metacpan/metacpan-api#618]
If you use the API to get releases, the entry for Term-Screen-Wizard doesn't have a **download_url**. You can see this by looking at:

> [fastapi.metacpan.org/release/Term-Screen-Wizard](https://fastapi.metacpan.org/release/Term-Screen-Wizard)

If you look in the [author's CPAN directory](http://www.cpan.org/authors/id/O/OE/OESTERHOL/), you'll see that the release tarball is there.

Cheers,
Neil

**Comment by oalders** [comment]
Hi Neil,

I've re-indexed it manually.  The `download_url` is there now.  We should probably have some kind of check in place to ensure this doesn't happen again.
