### ISSUE TITLE
Ensure that PAUSE custodial accounts always clobber existing author name

### ISSUE THREAD

**Issue by oalders** [metacpan/metacpan-api#621]
Related to #620  It appears that `AVENJ` is not yet listed with the "custodial" name.  We need to make sure this happens automatically.

**Comment by ranguard** [comment]
I think we should _only_ use PAUSE data (where the user has associated a PAUSE account), `authors.json` and our own UI data should only be for additional fields we are unable to get from PAUSE.

One `true` source is much clearer for everyone, and it should then be documented as such (including through our UI making it clear which fields are not editable and why)

**Comment by mickeyn** [comment]
there seem to be an issue with profile update that runs over the data set by the author script. i suspect the bug is in `profile_PUT` which is completely running over the entry in the index so fields like `is_pause_custodial_account` just disappear from the record.

will try to fix soon.

**Comment by mickeyn** [comment]
I wrongly thought this matter was resolved already, but apparently not.
For `AVENJ` I see the `name` field doesn't contain `(PAUSE Custodial Account)`... not sure why *that* is, but it does affect the setting of `is_pause_custodial_account`.

@oalders any idea?
