### ISSUE TITLE
06perms script needs to handle modules which are deleted

### ISSUE THREAD

**Issue by oalders** [metacpan/metacpan-api#630]
We need to handle this gracefully rather than doing a bulk delete and re-insert.

**Comment by mickeyn** [comment]
#644 added `--clean_up` flag to handle removed packages.
Running in this mode takes longer than the 10m interval we run the permission cron in.
As agreed (in PTS) we should run in cleanup mode once a day.

**Comment by mickeyn** [comment]
https://github.com/metacpan/metacpan-puppet/pull/126 should fix this one.

**Comment by mickeyn** [comment]
crons changes are merged. closing.
