### ISSUE TITLE
Provide OS and package information if the distribution is packaged

### ISSUE THREAD

**Issue by book** [metacpan/metacpan-api#634]
This is similar to  #154 and metacpan/metacpan-web#919.

Many CPAN distributions are available as packages for Linux distributions. This information would be useful to show on a distribution page on metacpan, and also through the API.

I have worked out the mapping for Debian, and [this script](https://github.com/book/CPANio/blob/master/bin/cpan-packaged-debian) produces [a JSON file](http://cpan.io/dists-in/debian.json) with the data.

I'd like to discuss the options for:
* including the Debian package info in metacpan and API results (either by generating it on the metacpan infrastructure, or pulling it from my files)
* a better, more useful format for the source data, if needed
* come up with a general way for importing that metadata for other package systems (RedHat and Fedora RPM, ActiveState PPM, Arch pacman, Gentoo ebuild, etc)

**Comment by oalders** [comment]
I believe that this should live in the `distribution` endpoint.  We could follow a pattern similar to this one https://github.com/metacpan/metacpan-api/pull/462

For the other issues, you could step over into the MetaCPAN room and we could discuss it face to face.  :)

**Comment by mickeyn** [comment]
the script will be introduced in #637 
we'll just need to add the mapping manually before running and set up a cron.

**Comment by mickeyn** [comment]
with the merging of #637 we can wrap this up today

**Comment by mickeyn** [comment]
@book can we close this one?
