### ISSUE TITLE
Backfill 'main_module' data for older dists

### ISSUE THREAD

**Issue by akarelas** [metacpan/metacpan-api#649]
I believe the main_module field doesn't exist on old releases. Could you please fill it with data in the old releases, so that my tool (which auto-generates a cpanfile) will work better?

**Comment by oalders** [comment]
This release from 2002 has `main_module`, so I'll assume this has now been backfilled.  We can re-open if that's not the case.

https://explorer.metacpan.org/?url=/release/LDS/CGI.pm-2.88
