### ISSUE TITLE
Method name conflict in roles 'MetaCPAN::Script::Role::External::Debian' and 'MetaCPAN::Script::Role::External::Fedora',

### ISSUE THREAD

**Issue by oalders** [metacpan/metacpan-api#670]
"Due to a method name conflict in roles 'MetaCPAN::Script::Role::External::Debian' and 'MetaCPAN::Script::Role::External::Fedora', the method 'dist_for' must be implemented or excluded by 'MetaCPAN::Script::External' at /home/metacpan/carton/metacpan-api/lib/perl5/x86_64-linux/Moose/Exporter.pm line 419
	Moose::with('MetaCPAN::Role::Script', 'MooseX::Getopt', 'MetaCPAN::Script::Role::External::Cygwin', 'MetaCPAN::Script::Role::External::Debian', 'MetaCPAN::Script::Role::External::Fedora') called at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Script/External.pm line 12
	require MetaCPAN/Script/External.pm at /home/metacpan/carton/metacpan-api/lib/perl5/Module/Runtime.pm line 317
	Module::Runtime::require_module('MetaCPAN::Script::External') called at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Script/Runner.pm line 19
	MetaCPAN::Script::Runner::run('MetaCPAN::Script::Runner') called at bin/metacpan line 21
Compilation failed in require at /home/metacpan/carton/metacpan-api/lib/perl5/Module/Runtime.pm line 317, <DATA> line 2125."

Paging @book and @mickeyn.  I know the actually testing is non-trivial, but is there maybe a compilation test we can add to catch this kind of thing in future?

**Comment by mickeyn** [comment]
sure. I created and will merge (as soon as travis finishes) the name conflict fix.
next I'll try to create a test for the these scripts.

**Comment by oalders** [comment]
@mickeyn can we close this now?

**Comment by mickeyn** [comment]
we didn't do anything about it... but let's close and review again if needed.
