### ISSUE TITLE
Automate tagging

### ISSUE THREAD

**Issue by monken** [metacpan/metacpan-api#71]
Use ElasticSearch's percolate feature to automate the tagging of modules:

http://www.elasticsearch.org/guide/reference/api/percolate.html

A release document is sent to the ES server and ES returns a list of matching tags.

Examples: 
- abstract contains "deprecated" => tag as deprecated
- dependency contains XSLoader => tag as XS code
- dependency contains Moose ...

**Comment by ranguard** [comment]
No movement for so long - closing
