### ISSUE TITLE
What Happened to Number-Phone?

### ISSUE THREAD

**Issue by theory** [metacpan/metacpan-api#712]
A new release of Number-Phone came out last week. You can see it [here](http://search.cpan.org/dist/Number-Phone/) on search.cpan.org. It appears to be missing from MetaCPAN, though; [the release API](http://fastapi.metacpan.org/v1/release/Number-Phone) 404s. Any idea what happened to it?

**Comment by oalders** [comment]
See #709.

**Comment by theory** [comment]
So, close as dupe?

**Comment by oalders** [comment]
Sounds fair!
