### ISSUE TITLE
Email-MIME-RFC2047 -- not the latest version

### ISSUE THREAD

**Issue by Corin-EU** [metacpan/metacpan-api#726]
In advance, sorry if this issue is being reported in the wrong place, but after much searching this seems appropriate to report here ...

If I go to the MetaCPAN web page for "Email::MIME::RFC2047" at

https://metacpan.org/release/Email-MIME-RFC2047

it correctly shows that the latest version is 0.95 (of May 14, 2016) and the web page has a **Download** link to the latest version 0.95 tar.gz file and a **Latest version** link to a page on search.cpan.org showing the latest version as 0.95.

But if I use the MetaCPAN API in a script or go to 

https://fastapi.metacpan.org/v1/download_url/Email::MIME::RFC2047

the version is shown as 0.93 (of October 5, 2015, two previous versions ago).

Can this be rectified in the MetaCPAN API or is it some indexing problem on ww.cpan.org that nobody on cpan.org will bother to fix, because if I use the latest  cpan (script) to get Email-MIME-RFC2047 , it downloads the old version 0.93, not the latest 0.95.

Upon checking the contents of the latest 02.packages.details.txt file, the reason why the 0.93 version is downloaded is revealed, but all the individual module contents are listed as 0.95.

    Email::MIME::RFC2047               0.93  N/NW/NWELLNHOF/Email-MIME-RFC2047-0.93.tar.gz
    Email::MIME::RFC2047::Address      0.95  N/NW/NWELLNHOF/Email-MIME-RFC2047-0.95.tar.gz
    Email::MIME::RFC2047::AddressList  0.95  N/NW/NWELLNHOF/Email-MIME-RFC2047-0.95.tar.gz
    Email::MIME::RFC2047::Decoder      0.95  N/NW/NWELLNHOF/Email-MIME-RFC2047-0.95.tar.gz
    Email::MIME::RFC2047::Encoder      0.95  N/NW/NWELLNHOF/Email-MIME-RFC2047-0.95.tar.gz
    Email::MIME::RFC2047::Group        0.95  N/NW/NWELLNHOF/Email-MIME-RFC2047-0.95.tar.gz
    Email::MIME::RFC2047::Mailbox      0.95  N/NW/NWELLNHOF/Email-MIME-RFC2047-0.95.tar.gz
    Email::MIME::RFC2047::MailboxList  0.95  N/NW/NWELLNHOF/Email-MIME-RFC2047-0.95.tar.gz
    Email::MIME::RFC2047::Parser       0.95  N/NW/NWELLNHOF/Email-MIME-RFC2047-0.95.tar.gz

**Comment by oalders** [comment]
So, this problem is with `02packages`.  I had a quick look and don't see the actual problem.  Maybe @nwellnhof needs PAUSE to re-index this upload?

**Comment by Corin-EU** [comment]
Thanks for looking into this and suggesting a possible fix.

Hopefully the author of the module @nwellnhof  will be able to resolve the indexing issue with the use of PAUSE.

**Comment by nwellnhof** [comment]
Fixed in Email::MIME::RFC2047 version 0.96.

**Comment by oalders** [comment]
Thanks @nwellnhof!

**Comment by Corin-EU** [comment]
All is now looking good via MetaCPAN api

        "date" : "2017-07-27T18:07:23",
        "version" : "0.96",
        "status" : "latest",
        "download_url" : "https://cpan.metacpan.org/authors/id/N/NW/NWELLNHOF/Email-MIME-RFC2047-0.96.tar.gz"

Thank you for helping to resolve the issue.
