### ISSUE TITLE
reverse_dependencies endpoint ignores size and always returns 50 elements

### ISSUE THREAD

**Issue by autarch** [metacpan/metacpan-api#736]
See https://fastapi.metacpan.org/v1/reverse_dependencies/dist/Code-TidyAll?q=status:latest&size=1

This led me to report a bug for `MetaCPAN::Client` that I've since closed - https://github.com/metacpan/metacpan-client/issues/91

But I'm fairly certain the problem is that the problem is the server.

Also, I'm a little unclear on whether it should be `size` or `page_size`, but either way I still get 50 results.

**Comment by oalders** [comment]
@mickeyn perhaps related to some of your changes?

**Comment by mickeyn** [comment]
maybe... #738 will fix it

**Comment by horgh** [comment]
Was this actually fixed? I can't get more than 50 when trying to look up reverse dependencies. e.g. look up Clone.

It looks like page_size is the parameter. I can reduce how many results I get from 50, but can't go beyond 50.

**Comment by horgh** [comment]
Well given I can go below 50 it's not ignored, so I guess it's a different issue that I can't go beyond 50. Should I be able to?

**Comment by mickeyn** [comment]
I'll check it. the parameter does go into the ES query and the results are not trimmed by our code.
Might be an ES setting limitation or Search::Elasticsearch issue - I'll try to find out soon.

**Comment by mickeyn** [comment]
This is now fixed.
