### ISSUE TITLE
UAV-Pilot incorrect versions

### ISSUE THREAD

**Issue by bmckalla** [metacpan/metacpan-api#809]
Five different versions are indicated as 0.10, only four are correct.

https://fastapi.metacpan.org/release
{
  "query": {
      "bool": {
          "must": [{"term": {"distribution": "UAV-Pilot"}}, 
                   {"term": {"version": "0.10"}}]
          }
    },
  "fields": ["version", "name"]
}

**Comment by bmckalla** [comment]
Same goes for UAV-Pilot-ARDrone for version 0.2

{
  "query": {
      "bool": {
          "must": [{"term": {"distribution": "UAV-Pilot-ARDrone"}}, 
                   {"term": {"version": "0.2"}}]
          }
    },
  "fields": ["version", "name"]
}

**Comment by haarg** [comment]
The version field is taken from the dist metadata.  These are all correct.
