### ISSUE TITLE
A search on Mail::Sendmail turns up a non-indexed copy in Test-Smoke

### ISSUE THREAD

**Issue by neilb** [metacpan/metacpan-api#811]
Mail::Sendmail is released in Mail-Sendmail, for which I have co-maint. My latest release is what's in the CPAN Index:

    Mail::Sendmail                     0.80  N/NE/NEILB/Mail-Sendmail-0.80.tar.gz

The Test-Smoke distribution (from ABELTJE) has a copy of this module bundled with it, in the `inc/` directory. The dist's metadata has an explicit `no_index` against the `inc/`, which is why when Abe releases Test-Smoke, his copy of Mail::Sendmail doesn't get indexed, even though he has co-maint on Mail::Sendmail.

I'll probably ask Abe if it's ok to drop the co-maint, as I don't think he needs it, but this is still a MetaCPAN bug as well.

**Comment by oalders** [comment]
```bash
2018/05/17 14:58:33 I release: Downloading https://cpan.metacpan.org/authors/id/N/NE/NEILB/Mail-Sendmail-0.80.tar.gz
2018/05/17 14:58:38 I release: Processing /home/metacpan/metacpan-api/var/tmp/http/authors/id/N/NE/NEILB/Mail-Sendmail-0.80.tar.gz
2018/05/17 14:58:50 I release: Mail-Sendmail consists of 1 modules
2018/05/17 14:58:51 I release: Upgrading release Mail-Sendmail-0.80
2018/05/17 14:58:51 I release: Downgrading release Test-Smoke-1.72
```

**Comment by Grinnz** [comment]
Possibly similar to #592

**Comment by Daniel-Beardsmore** [comment]
Has this been forgotten? The issue persists and indeed it is quite confusing — if it weren’t for finding 0.8 in cPanel I would not even know that 0.8 exists.

**Comment by oalders** [comment]
I realize this doesn't fix the root cause, but @abeltje would you be willing to give up permissions on https://metacpan.org/permission/distribution/Mail-Sendmail ?

**Comment by abeltje** [comment]
Hi all,

I never knew I got (or wanted) co-maint for Mail-Sendmail. Feel free to remove them.

Good luck,

-- Abe.

**Comment by neilb** [comment]
Thanks Abe -- I'll drop that shortly and confirm to you in email.

**Comment by oalders** [comment]
@neilb can you let me know when that is done and I'll re-index?

**Comment by oalders** [comment]
Looks like this has been taken care of.
