### ISSUE TITLE
DMUEY/Locales doesn't appear on MetaCPAN

### ISSUE THREAD

**Issue by remorse** [metacpan/metacpan-api#812]
Hi! Given the news that search.cpan.org is going away, I thought I should bring up that DMUEY/Locales is not available via MetaCPAN. Even if you go to the author listing, the module doesn't show up there. I do use this module.

http://search.cpan.org/~dmuey/Locales-0.34/lib/Locales.pm

https://metacpan.org/author/DMUEY

Thanks,
Ricky

**Comment by oalders** [comment]
Hi Ricky,

The module is here: https://metacpan.org/release/DMUEY/Locales-0.34 but it's not easily discoverable.  It looks like all versions of this module are on Backpan -- ie they've been deleted from CPAN.  You can get to it via the "all releases" link on the author page, which is https://metacpan.org/author/DMUEY/releases

I'm not saying this an acceptable workflow.  I'm just demonstrating how I found it. Maybe we could have a conversation about how to improve the UI for this sort of situation.

Thanks,
Olaf

**Comment by remorse** [comment]
I'm not sure I have a good idea about a better UI? On <http://search.cpan.org>, if you enter "locales" as the search term, it comes up as the first result. `cpanm` lets you install it with no problems. So I'm not sure why MetaCPAN thinks it's been deleted from CPAN; it seems to be there with no issues for me...

**Comment by mickeyn** [comment]
This looks like an issue of missing 'provides' in the META

@oalders we should figure out a workaround to this as this seems like a recurring issue with some releases.

**Comment by drmuey** [comment]
> This looks like an issue of missing 'provides' in the META

@mickeyn thanks, that was what I was originally told, however:

   - the [suggestion that it because `provides` is missing](https://rt.cpan.org/Ticket/Display.html?id=125178&results=fde4af406f4edca4084b8b2c51232218) appears to be a misnomer:
      - [`provides` is supposed to be optional](https://metacpan.org/pod/CPAN::Meta::Spec#provides)
      - others without it have all of their modules indexed
      - it was added back to the index by forcing a reindex from PAUSE

HTH

**Comment by drmuey** [comment]
@mickeyn cool thanks, let me know if you need anything from me!

**Comment by mickeyn** [comment]
release is now fixed in live, #832 is the patch used manually to index this one.

**Comment by drmuey** [comment]
Looks like is indexed, thanks. I'll try to get into the habit of generating a `provides` :)
