### ISSUE TITLE
`interesting_files` picking up duplicate files

### ISSUE THREAD

**Issue by zakame** [metacpan/metacpan-api#813]
Ref https://github.com/metacpan/metacpan-api/pull/803#discussion_r189096793

Due to changes in #803, `interesting_files` now returns duplicates (e.g. https://metacpan.org/release/Dist-Zilla#other.)  

![image](https://user-images.githubusercontent.com/110625/40265481-9ea5d850-5b6b-11e8-882b-6bf74dd15bf4.png)

Perhaps use [terms aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html) on the ES side, or simply filter unique values on the Perl (Query::File) side.

**Comment by zakame** [comment]
On closer look at the Dist::Zilla example above, the `dist.ini` aren't really duplicates, but actual distinct files that are in different places:

```
api_1                 |           {
api_1                 |             'release' => 'Dist-Zilla-6.012',
api_1                 |             'status' => 'latest',
api_1                 |             'name' => 'dist.ini',
api_1                 |             'author' => 'RJBS',
api_1                 |             'distribution' => 'Dist-Zilla',
api_1                 |             'path' => 'dist.ini'
api_1                 |           },
api_1                 |           {
api_1                 |             'status' => 'latest',
api_1                 |             'name' => 'dist.ini',
api_1                 |             'release' => 'Dist-Zilla-6.012',
api_1                 |             'author' => 'RJBS',
api_1                 |             'distribution' => 'Dist-Zilla',
api_1                 |             'path' => 'corpus/dist/AutoPrereqs/dist.ini'
api_1                 |           },
api_1                 |           {
api_1                 |             'author' => 'RJBS',
api_1                 |             'name' => 'dist.ini',
api_1                 |             'status' => 'latest',
api_1                 |             'release' => 'Dist-Zilla-6.012',
api_1                 |             'distribution' => 'Dist-Zilla',
api_1                 |             'path' => 'corpus/dist/DZ1/dist.ini'
api_1                 |           },
api_1                 |           {
api_1                 |             'path' => 'corpus/dist/AuthorDeps/dist.ini',
api_1                 |             'distribution' => 'Dist-Zilla',
api_1                 |             'release' => 'Dist-Zilla-6.012',
api_1                 |             'status' => 'latest',
api_1                 |             'name' => 'dist.ini',
api_1                 |             'author' => 'RJBS'
api_1                 |           },
api_1                 |           {
api_1                 |             'author' => 'RJBS',
api_1                 |             'release' => 'Dist-Zilla-6.012',
api_1                 |             'status' => 'latest',
api_1                 |             'name' => 'dist.ini',
api_1                 |             'path' => 'corpus/dist/DZ-NonAscii/dist.ini',
api_1                 |             'distribution' => 'Dist-Zilla'
api_1                 |           },
```

Given this context, I think it would be useful to report the full path of these other (possibly) interesting files on metacpan-web, like what is already being done for the "Provides" set.  @oalders @Grinnz what do you think?

**Comment by Grinnz** [comment]
No, dist.ini outside of the root is not interesting.

**Comment by zakame** [comment]
@oalders @Grinnz thanks for the guidance.  I suppose this should be something more easily done on the Perl side (e.g. a filter on the query results after fetching from ES.)  I'll whip up something this week (and perhaps another if I can find an ES-based solution, but would try to keep it simple) for you guys to check :muscle:

**Comment by oalders** [comment]
@zakame it looks like @haarg has done some work on this in https://github.com/metacpan/metacpan-api/compare/haarg/interesting-file-locations

**Comment by haarg** [comment]
Should be fixed now.

**Comment by zakame** [comment]
Thanks @haarg and everyone!
