### ISSUE TITLE
Debian script returns errors

### ISSUE THREAD

**Issue by mickeyn** [metacpan/metacpan-api#835]
@book - $subject: 

`DBI connect('host=public-udd-mirror.xvm.mit.edu;dbname=udd','public-udd-mirror',...) failed: could not connect to server: Connection timed out
        Is the server running on host "public-udd-mirror.xvm.mit.edu" (18.49.6.246) and accepting
        TCP/IP connections on port 5432? at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Script/Role/External/Debian.pm line 43.
Can't call method "prepare" on an undefined value at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Script/Role/External/Debian.pm line 64.`

**Comment by book** [comment]
It seems the address for the server has changed. I will submit a PR with the new address and credentials.
Details at <https://udd-mirror.debian.net/>.

**Comment by book** [comment]
The PR is #836.
