### ISSUE TITLE
`cpanm --dev` returns incorrect result

### ISSUE THREAD

**Issue by ribasushi** [metacpan/metacpan-api#839]
Current devrel of `DBD::Oracle` is [`1.75_42`](https://metacpan.org/release/DJZORT/DBD-Oracle-1.75_42). However `cpanm --dev DBD::Oracle` receives `1.75_2`

`curl -H 'User-Agent: cpanminus/1.7042 perl/5.016002' 'https://api.metacpan.org/v0/file/_search?source=%7B%22fields%22%3A%5B%22date%22%2C%22release%22%2C%22author%22%2C%22module%22%2C%22status%22%5D%2C%22query%22%3A%7B%22filtered%22%3A%7B%22query%22%3A%7B%22nested%22%3A%7B%22query%22%3A%7B%22custom_score%22%3A%7B%22query%22%3A%7B%22constant_score%22%3A%7B%22filter%22%3A%7B%22and%22%3A%5B%7B%22term%22%3A%7B%22module.authorized%22%3Atrue%7D%7D%2C%7B%22term%22%3A%7B%22module.indexed%22%3Atrue%7D%7D%2C%7B%22term%22%3A%7B%22module.name%22%3A%22DBD%3A%3AOracle%22%7D%7D%2C%7B%22range%22%3A%7B%22module.version_numified%22%3A%7B%22gte%22%3A%220.000%22%7D%7D%7D%5D%7D%7D%7D%2C%22metacpan_script%22%3A%22score_version_numified%22%7D%7D%2C%22score_mode%22%3A%22max%22%2C%22path%22%3A%22module%22%7D%7D%2C%22filter%22%3A%7B%22and%22%3A%5B%7B%22not%22%3A%7B%22term%22%3A%7B%22status%22%3A%22backpan%22%7D%7D%7D%5D%7D%7D%7D%7D'`

Returns:
```
{
   "hits" : {
      "hits" : [
         {
            "_score" : 1,
            "fields" : {
               "author" : "MJEVANS",
               "date" : "2014-11-19T09:10:30Z",
               "module" : [
                  {
                     "name" : "DBD::Oracle",
                     "version" : "1.75_2"
                  }
               ],
               "module.name" : "DBD::Oracle",
               "module.version" : "1.75_2",
               "release" : "DBD-Oracle-1.75_2",
               "status" : "cpan"
            }
         }
      ]
   },
   "x_metacpan_shim" : {
      "info" : "metacpan-api-v0-shim v0.001 - Only supports cpanm 1.7.  See https://github.com/metacpan/metacpan-api/blob/master/docs/API-docs.md for updated API documentation, and the /download_url/ end point for download information",
      "query" : {
         "dev" : 1,
         "module" : "DBD::Oracle"
      },
      "query_url" : "https://fastapi.metacpan.org/v1/download_url/DBD::Oracle?dev=1"
   }
}
```

/cc @haarg

**Comment by haarg** [comment]
DJZORT does not have permissions to release this module, so the _42 release is excluded from the dev option.  The same applies to ZARQUON.

**Comment by ribasushi** [comment]
My bad... for some reason I thought MJEVANS does *not* have perms either, thus my confusion. You are all around correct.
