### ISSUE TITLE
Geo::TigerLine

### ISSUE THREAD

**Issue by myrrhlin** [metacpan/metacpan-api#859]
a search on Geo::TigerLine doesn't turn up the distribution (only one module newly included in version 0.03)
  https://metacpan.org/search?q=Geo%3A%3ATigerLine

a direct link to it from the dependencies panel of Geo::Coder::US turns up nothing:
  https://metacpan.org/pod/Geo::TigerLine

but it exists, and has POD (version 0.03, released by EZARKO):
  https://metacpan.org/pod/distribution/Geo-TigerLine/lib/Geo/TigerLine.pm

The manifest for release 0.03 is under EZARKO, shown as unauthorized, except the one new module: 
  https://metacpan.org/release/EZARKO/Geo-TigerLine-0.03

The manifest for release 0.02 can be found under SDERLE:
  https://metacpan.org/release/SDERLE/Geo-TigerLine-0.02

$ curl -s http://cpan.metacpan.org/modules/06perms.txt.gz | zgrep Geo::TigerLine
Geo::TigerLine,SDERLE,f
Geo::TigerLine::Abbreviations,JJORE,f
Geo::TigerLine::Record,SDERLE,f
Geo::TigerLine::Record::1,SDERLE,f
Geo::TigerLine::Record::2,SDERLE,f
Geo::TigerLine::Record::3,SDERLE,f
Geo::TigerLine::Record::4,SDERLE,f
Geo::TigerLine::Record::5,SDERLE,f
Geo::TigerLine::Record::6,SDERLE,f
Geo::TigerLine::Record::7,SDERLE,f
Geo::TigerLine::Record::8,SDERLE,f
Geo::TigerLine::Record::9,SDERLE,f
Geo::TigerLine::Record::A,SDERLE,f
Geo::TigerLine::Record::Accessor,SDERLE,f
Geo::TigerLine::Record::B,SDERLE,f
Geo::TigerLine::Record::C,SDERLE,f
Geo::TigerLine::Record::E,SDERLE,f
Geo::TigerLine::Record::H,SDERLE,f
Geo::TigerLine::Record::I,SDERLE,f
Geo::TigerLine::Record::M,EZARKO,f
Geo::TigerLine::Record::P,SDERLE,f
Geo::TigerLine::Record::Parser,SDERLE,f
Geo::TigerLine::Record::R,SDERLE,f
Geo::TigerLine::Record::S,SDERLE,f
Geo::TigerLine::Record::T,SDERLE,f
Geo::TigerLine::Record::U,SDERLE,f
Geo::TigerLine::Record::Z,SDERLE,f

$ curl -s https://cpan.metacpan.org/modules/02packages.details.txt | grep Geo::TigerLine
Geo::TigerLine                     0.02  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz
Geo::TigerLine::Abbreviations      0.04  J/JJ/JJORE/Geo-TigerLine-Abbreviations-0.04.tar.gz
Geo::TigerLine::Record             0.01  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz
Geo::TigerLine::Record::1          0.02  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz
Geo::TigerLine::Record::2          0.02  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz
Geo::TigerLine::Record::4          0.02  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz
Geo::TigerLine::Record::5          0.02  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz
Geo::TigerLine::Record::6          0.02  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz
Geo::TigerLine::Record::7          0.02  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz
Geo::TigerLine::Record::8          0.02  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz
Geo::TigerLine::Record::A          0.02  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz
Geo::TigerLine::Record::Accessor   0.02  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz
Geo::TigerLine::Record::B          0.02  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz
Geo::TigerLine::Record::C          0.02  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz
Geo::TigerLine::Record::E          0.02  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz
Geo::TigerLine::Record::H          0.02  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz
Geo::TigerLine::Record::I          0.02  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz
Geo::TigerLine::Record::M          0.03  E/EZ/EZARKO/Geo-TigerLine-0.03.tar.gz
Geo::TigerLine::Record::P          0.02  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz
Geo::TigerLine::Record::Parser     0.01  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz
Geo::TigerLine::Record::R          0.02  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz
Geo::TigerLine::Record::S          0.02  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz
Geo::TigerLine::Record::T          0.02  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz
Geo::TigerLine::Record::U          0.02  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz
Geo::TigerLine::Record::Z          0.02  S/SD/SDERLE/Geo-TigerLine-0.02.tar.gz

apparently EZARKO, who released 0.03, is only authorized for the one new
module, and nobody is currently authorized to release any of the other 
modules in the distribution:

https://metacpan.org/permission/distribution/Geo-TigerLine

Perhaps permissions need adjusting on this module?
Would re-indexing this distribution help?

metacpan could be a bit more helpful when these kinds of situations occur (at least giving
some results, rather than none!)

**Comment by oalders** [comment]
@andk do you know, historically, what happened with this modules?  Do the perms need updating?

**Comment by mickeyn** [comment]
So after a discussion, our decision is to wait until perms is updated so EZARKO have permissions to all packages in the release (can be done by SDERLE or a PAUSE admin) before we reindex.
Alternatively, a new release by someone with the proper permissions will solve the issue.
Closing this for now, please poke us when we can take action.

**Comment by myrrhlin** [comment]
my ticket was not necessarily about the permissions mess of this package per se, but how metacpan handles it.  obviously nothing prevents such messes from existing, but metacpan should make fewer assumptions about these things, so that you can still search and find stuff, even in these situations.
