### ISSUE TITLE
The cpanminus-specific v0 api endpoint throws 502

### ISSUE THREAD

**Issue by ribasushi** [metacpan/metacpan-api#882]
A request like the one in https://github.com/metacpan/metacpan-api/issues/839#issue-360699393 no longer completes, resulting in:
```
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

This gateway is still in heavy use for finding older versions of backpanned  things like `cpanm --mirror http://cpan.metacpan.org/ --look DBD::SQLite@1.29`

**Comment by haarg** [comment]
The service was not running, I'm assuming due to the changes to starman startup that were made.  Working now.

We should add some kind of monitoring to this endpoint.

**Comment by haarg** [comment]
Monitor added.
