### ISSUE TITLE
Dockerfile: parameratize `CMD` statement

### ISSUE THREAD

**Issue by ssoriche** [metacpan/metacpan-api#891]
Right now the `CMD` specification is:

```
CMD [ "/wait-for-it.sh", "db:5432", "--", "carton", "exec", "morbo", "-l", "http://*:5000", "-w", "root", "./bin/api.pl"]
```

This works well as long as you are running in the `metacpan-docker` environment and want to run `morbo` as the server. However, flexibility can be added by replacing the `db:5432` with an environment variable containing the database connection to try and establish, and creating variables for which server should be executed.

The default values can be those that are already specified as they should work for what developers want 90% of the time.

**Comment by jonasbn** [comment]
This issue seems outdated, if you look at the current state of the `Dockerfile`

**Comment by oalders** [comment]
@ssoriche can we close this?
