### ISSUE TITLE
Unable to link my PAUSE account: mail forward not working

### ISSUE THREAD

**Issue by telatin** [metacpan/metacpan-api#920]
Dear all,
first of all i <3 MetaCPAN so thanks for your work!

I have a MetaCPAN account made with my GitHub credential, but I'm not able to link my PAUSE account because I never receive my pro**@cpan.org emails.

See screenshot from PAUSE: https://mobile.twitter.com/telatin/status/1139138454175064064/photo/1

I have to admit that when I created the PAUSE account I didnt initally set the redirect, but I updated the settings a month ago and apparently I'm not able to receive emails. If I send to myself an email to the cpan.org domain I get the delivery system notification with this error:
`554 5.7.1 <proch@cpan.org>: Recipient address rejected: Access denied`

I didnt find a proper contact in the PAUSE website, hence I'm adding this issue here. Thanks

**Comment by oalders** [comment]
I wonder if this is related to https://github.com/andk/pause/issues/339  @andk what do you think?

**Comment by telatin** [comment]
Looks like. I'll follow that thread
