### ISSUE TITLE
/release/{distribution} doesn't exist for all {distribution}

### ISSUE THREAD

**Issue by timsnyder** [metacpan/metacpan-api#923]
This seems like a bug.  I've searched quite a bit in your existing issues.  Please forgive me if this is user-error.

https://fastapi.metacpan.org/v1/release/Test-Synopsis 404's but https://fastapi.metacpan.org/v1/release/ZOFFIX/Test-Synopsis-0.16 gives much JSON goodness.
https://fastapi.metacpan.org/v1/module/Test::Synopsis also seems to work as expected.

Am I missing something or is this a bug?

**Comment by Grinnz** [comment]
The latest release of that distribution does not appear to be marked as "latest" though [it is indexed by PAUSE](https://cpanmeta.grinnz.com/packages?module=Test%3A%3ASynopsis&match_mode=exact). Probably just needs to be reindexed by metacpan.

**Comment by timsnyder** [comment]
Thanks for the quick reply. It looks like v0.16 of the distribution was released several months ago (may). How often does the metacpan indexing happen?

**Comment by Grinnz** [comment]
It normally only happens just after the release. This probably needs to be redone manually.

**Comment by oalders** [comment]
Thanks @timbunce and @Grinnz.  I've just re-indexed this manually.  It should be working now.

**Comment by timsnyder** [comment]
It is.  Thanks Olaf!
