### ISSUE TITLE
reverse dependencies list incorrectly includes "conflicts"

### ISSUE THREAD

**Issue by karenetheridge** [metacpan/metacpan-api#957]
Much to my surprise I found Mouse in Any-Moose's reverse dependencies list. Investigating, it looks like it's coming from this entry in META.json:

https://metacpan.org/source/SKAJI/Mouse-v2.5.10/META.json#L60

"conflicts" is not a normal prerequisite phase and is not indicating something that needs to be or even is suggested as being installed for the distribution. It should not be included in dependency graph calculations.

**Comment by oalders** [comment]
Closed via #996
