### ISSUE TITLE
Document download_url

### ISSUE THREAD

**Issue by oalders** [metacpan/metacpan-api#983]
If we have documented this API, it's not easy to find:

https://github.com/metacpan/metacpan-api/blob/master/t/server/controller/download_url.t#L16-L66

**Comment by szabgab** [comment]
Are you looking for an entry in the FAQ explaining how to download older versions of a distribution?

**Comment by oalders** [comment]
Actually, I see that it *is* documented at https://github.com/metacpan/metacpan-api/blob/master/docs/API-docs.md#download_urlmodule I think we can close this?
