### ISSUE TITLE
Replace Travis config with CircleCI

### ISSUE THREAD

**Issue by oalders** [metacpan/metacpan-api#994]

**Comment by szabgab** [comment]
Would you be interested in a GitHub Actions configuration?

**Comment by oalders** [comment]
We did have GitHub Actions configured, but because of the way we were testing with Docker, GitHub would kill the build with no explanation. By the time I heard back from their support I had already moved over to CircleCI, which is much easier to work with, since you can SSH in to the VM to poke at the build. Also CircleCI gives us the option of upgrading to bigger and faster VMs in the future, so that's something to consider. ie if we get together for a hackathon, we can use faster VMs and have less time waiting on builds.

Having said that, what Travis is doing is creating build artifacts (cpanfile.snapshot) and pushing to Docker hub. Those things could be done in GitHub Actions or they could just be configured to happen in CircleCI as build steps.

**Comment by ranguard** [comment]
I feel like this is done - please re-open if not!
