### ISSUE TITLE
Anchor names in the generated HTML docs: “-” vs. “_”

### ISSUE THREAD

**Issue by ilyaza** [metacpan/metacpan-api#995]
CPAN-search and METACPAN are important resources if one wants to link to (sections in) documentation of Perl modules.  However, it seems that recently¹⁾ the style of generated anchor links changed — so the links to subsections do not work anymore.  RESULT: links in existing documents stopped to work.

 ¹⁾ I did not check for some time, so it could be several months (a year?).

Before, the links were generated with `#Some_words_in_name`; now they are generated as `#Some-words-in-name`.  (So underscores are replaced with dashes.)  

I understand that this is due to a change to uplevel Perl code.  But is it possible to do something about this?  (Such as generate both `<a name=FOO>` wrappers?

**Comment by Grinnz** [comment]
Do you have an example of such links? The anchors have worked like this for years, and https://metacpan.org/pod/Pod::Simple::Role::XHTML::WithAccurateTargets adds the more useful anchors.

**Comment by ilyaza** [comment]
(http://search.cpan.org/~ilyaz/UI-KeyboardLayout/lib/UI/KeyboardLayout.pm#There_is_no_way_to_show_Unicode_contents_on_Windows)[http://search.cpan.org/~ilyaz/UI-KeyboardLayout/lib/UI/KeyboardLayout.pm#There_is_no_way_to_show_Unicode_contents_on_Windows]

This is the 2nd link on the 1st line in the “Resources” subsection of [http://k.ilyaz.org](http://k.ilyaz.org) (about 20 lines down).  It used to work.

**Comment by Grinnz** [comment]
search.cpan.org was a different website and metacpan is not responsible for what it may have used as anchors. Only link forwarding is provided.

**Comment by ilyaza** [comment]
This is a very plausible explanation.  I may miss checking such particular links after the mirroring was switched on.

Nevertheless: is it possible to correct the links **during** mirroring?

**Comment by Grinnz** [comment]
No - URL fragments are not sent to the server, they are only used by the browser once the final page is received.

**Comment by ilyaza** [comment]
Right — I may have noticed it myself.  Sorry!

Seems to be no good solution available…

**Comment by oalders** [comment]
Thanks for raising the issue, @ilyaza. :)
